// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: terraform/v1/terraform.proto

package terraformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/terraform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TerraformServiceName is the fully-qualified name of the TerraformService service.
	TerraformServiceName = "terraform.v1.TerraformService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TerraformServiceInitProcedure is the fully-qualified name of the TerraformService's Init RPC.
	TerraformServiceInitProcedure = "/terraform.v1.TerraformService/Init"
	// TerraformServicePlanProcedure is the fully-qualified name of the TerraformService's Plan RPC.
	TerraformServicePlanProcedure = "/terraform.v1.TerraformService/Plan"
	// TerraformServiceApplyProcedure is the fully-qualified name of the TerraformService's Apply RPC.
	TerraformServiceApplyProcedure = "/terraform.v1.TerraformService/Apply"
)

// TerraformServiceClient is a client for the terraform.v1.TerraformService service.
type TerraformServiceClient interface {
	Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error)
	Plan(context.Context, *connect.Request[v1.PlanRequest]) (*connect.Response[v1.PlanResponse], error)
	Apply(context.Context, *connect.Request[v1.ApplyRequest]) (*connect.Response[v1.ApplyResponse], error)
}

// NewTerraformServiceClient constructs a client for the terraform.v1.TerraformService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTerraformServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TerraformServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	terraformServiceMethods := v1.File_terraform_v1_terraform_proto.Services().ByName("TerraformService").Methods()
	return &terraformServiceClient{
		init: connect.NewClient[v1.InitRequest, v1.InitResponse](
			httpClient,
			baseURL+TerraformServiceInitProcedure,
			connect.WithSchema(terraformServiceMethods.ByName("Init")),
			connect.WithClientOptions(opts...),
		),
		plan: connect.NewClient[v1.PlanRequest, v1.PlanResponse](
			httpClient,
			baseURL+TerraformServicePlanProcedure,
			connect.WithSchema(terraformServiceMethods.ByName("Plan")),
			connect.WithClientOptions(opts...),
		),
		apply: connect.NewClient[v1.ApplyRequest, v1.ApplyResponse](
			httpClient,
			baseURL+TerraformServiceApplyProcedure,
			connect.WithSchema(terraformServiceMethods.ByName("Apply")),
			connect.WithClientOptions(opts...),
		),
	}
}

// terraformServiceClient implements TerraformServiceClient.
type terraformServiceClient struct {
	init  *connect.Client[v1.InitRequest, v1.InitResponse]
	plan  *connect.Client[v1.PlanRequest, v1.PlanResponse]
	apply *connect.Client[v1.ApplyRequest, v1.ApplyResponse]
}

// Init calls terraform.v1.TerraformService.Init.
func (c *terraformServiceClient) Init(ctx context.Context, req *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error) {
	return c.init.CallUnary(ctx, req)
}

// Plan calls terraform.v1.TerraformService.Plan.
func (c *terraformServiceClient) Plan(ctx context.Context, req *connect.Request[v1.PlanRequest]) (*connect.Response[v1.PlanResponse], error) {
	return c.plan.CallUnary(ctx, req)
}

// Apply calls terraform.v1.TerraformService.Apply.
func (c *terraformServiceClient) Apply(ctx context.Context, req *connect.Request[v1.ApplyRequest]) (*connect.Response[v1.ApplyResponse], error) {
	return c.apply.CallUnary(ctx, req)
}

// TerraformServiceHandler is an implementation of the terraform.v1.TerraformService service.
type TerraformServiceHandler interface {
	Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error)
	Plan(context.Context, *connect.Request[v1.PlanRequest]) (*connect.Response[v1.PlanResponse], error)
	Apply(context.Context, *connect.Request[v1.ApplyRequest]) (*connect.Response[v1.ApplyResponse], error)
}

// NewTerraformServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTerraformServiceHandler(svc TerraformServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	terraformServiceMethods := v1.File_terraform_v1_terraform_proto.Services().ByName("TerraformService").Methods()
	terraformServiceInitHandler := connect.NewUnaryHandler(
		TerraformServiceInitProcedure,
		svc.Init,
		connect.WithSchema(terraformServiceMethods.ByName("Init")),
		connect.WithHandlerOptions(opts...),
	)
	terraformServicePlanHandler := connect.NewUnaryHandler(
		TerraformServicePlanProcedure,
		svc.Plan,
		connect.WithSchema(terraformServiceMethods.ByName("Plan")),
		connect.WithHandlerOptions(opts...),
	)
	terraformServiceApplyHandler := connect.NewUnaryHandler(
		TerraformServiceApplyProcedure,
		svc.Apply,
		connect.WithSchema(terraformServiceMethods.ByName("Apply")),
		connect.WithHandlerOptions(opts...),
	)
	return "/terraform.v1.TerraformService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TerraformServiceInitProcedure:
			terraformServiceInitHandler.ServeHTTP(w, r)
		case TerraformServicePlanProcedure:
			terraformServicePlanHandler.ServeHTTP(w, r)
		case TerraformServiceApplyProcedure:
			terraformServiceApplyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTerraformServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTerraformServiceHandler struct{}

func (UnimplementedTerraformServiceHandler) Init(context.Context, *connect.Request[v1.InitRequest]) (*connect.Response[v1.InitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("terraform.v1.TerraformService.Init is not implemented"))
}

func (UnimplementedTerraformServiceHandler) Plan(context.Context, *connect.Request[v1.PlanRequest]) (*connect.Response[v1.PlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("terraform.v1.TerraformService.Plan is not implemented"))
}

func (UnimplementedTerraformServiceHandler) Apply(context.Context, *connect.Request[v1.ApplyRequest]) (*connect.Response[v1.ApplyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("terraform.v1.TerraformService.Apply is not implemented"))
}
