// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: lock/v1/lock.proto

package lockv1

import (
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/user/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Owner         *v1.User               `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Info          string                 `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_lock_v1_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{0}
}

func (x *Lock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lock) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Lock) GetOwner() *v1.User {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Lock) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Lock) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lock) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Owner         *v1.User               `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Info          *string                `protobuf:"bytes,3,opt,name=info,proto3,oneof" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLockRequest) Reset() {
	*x = CreateLockRequest{}
	mi := &file_lock_v1_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockRequest) ProtoMessage() {}

func (x *CreateLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockRequest.ProtoReflect.Descriptor instead.
func (*CreateLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLockRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateLockRequest) GetOwner() *v1.User {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *CreateLockRequest) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

type CreateLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *Lock                  `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLockResponse) Reset() {
	*x = CreateLockResponse{}
	mi := &file_lock_v1_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLockResponse) ProtoMessage() {}

func (x *CreateLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLockResponse.ProtoReflect.Descriptor instead.
func (*CreateLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLockResponse) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type GetLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockRequest) Reset() {
	*x = GetLockRequest{}
	mi := &file_lock_v1_lock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockRequest) ProtoMessage() {}

func (x *GetLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockRequest.ProtoReflect.Descriptor instead.
func (*GetLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{3}
}

func (x *GetLockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *Lock                  `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLockResponse) Reset() {
	*x = GetLockResponse{}
	mi := &file_lock_v1_lock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLockResponse) ProtoMessage() {}

func (x *GetLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLockResponse.ProtoReflect.Descriptor instead.
func (*GetLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{4}
}

func (x *GetLockResponse) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type DeleteLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockRequest) Reset() {
	*x = DeleteLockRequest{}
	mi := &file_lock_v1_lock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockRequest) ProtoMessage() {}

func (x *DeleteLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockRequest.ProtoReflect.Descriptor instead.
func (*DeleteLockRequest) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLockResponse) Reset() {
	*x = DeleteLockResponse{}
	mi := &file_lock_v1_lock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLockResponse) ProtoMessage() {}

func (x *DeleteLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_v1_lock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLockResponse.ProtoReflect.Descriptor instead.
func (*DeleteLockResponse) Descriptor() ([]byte, []int) {
	return file_lock_v1_lock_proto_rawDescGZIP(), []int{6}
}

var File_lock_v1_lock_proto protoreflect.FileDescriptor

const file_lock_v1_lock_proto_rawDesc = "" +
	"\n" +
	"\x12lock/v1/lock.proto\x12\alock.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12user/v1/user.proto\"\xe8\x01\n" +
	"\x04Lock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12#\n" +
	"\x05owner\x18\x03 \x01(\v2\r.user.v1.UserR\x05owner\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x87\x01\n" +
	"\x11CreateLockRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12(\n" +
	"\x05owner\x18\x02 \x01(\v2\r.user.v1.UserB\x03\xe0A\x02R\x05owner\x12\x17\n" +
	"\x04info\x18\x03 \x01(\tH\x00R\x04info\x88\x01\x01B\a\n" +
	"\x05_info\"7\n" +
	"\x12CreateLockResponse\x12!\n" +
	"\x04lock\x18\x01 \x01(\v2\r.lock.v1.LockR\x04lock\"%\n" +
	"\x0eGetLockRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"4\n" +
	"\x0fGetLockResponse\x12!\n" +
	"\x04lock\x18\x01 \x01(\v2\r.lock.v1.LockR\x04lock\"(\n" +
	"\x11DeleteLockRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x14\n" +
	"\x12DeleteLockResponse2\xd9\x01\n" +
	"\vLockService\x12E\n" +
	"\n" +
	"CreateLock\x12\x1a.lock.v1.CreateLockRequest\x1a\x1b.lock.v1.CreateLockResponse\x12<\n" +
	"\aGetLock\x12\x17.lock.v1.GetLockRequest\x1a\x18.lock.v1.GetLockResponse\x12E\n" +
	"\n" +
	"DeleteLock\x12\x1a.lock.v1.DeleteLockRequest\x1a\x1b.lock.v1.DeleteLockResponseB=Z;github.com/terrabase-dev/terrabase-sdk/specs/lock/v1;lockv1b\x06proto3"

var (
	file_lock_v1_lock_proto_rawDescOnce sync.Once
	file_lock_v1_lock_proto_rawDescData []byte
)

func file_lock_v1_lock_proto_rawDescGZIP() []byte {
	file_lock_v1_lock_proto_rawDescOnce.Do(func() {
		file_lock_v1_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lock_v1_lock_proto_rawDesc), len(file_lock_v1_lock_proto_rawDesc)))
	})
	return file_lock_v1_lock_proto_rawDescData
}

var file_lock_v1_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lock_v1_lock_proto_goTypes = []any{
	(*Lock)(nil),                  // 0: lock.v1.Lock
	(*CreateLockRequest)(nil),     // 1: lock.v1.CreateLockRequest
	(*CreateLockResponse)(nil),    // 2: lock.v1.CreateLockResponse
	(*GetLockRequest)(nil),        // 3: lock.v1.GetLockRequest
	(*GetLockResponse)(nil),       // 4: lock.v1.GetLockResponse
	(*DeleteLockRequest)(nil),     // 5: lock.v1.DeleteLockRequest
	(*DeleteLockResponse)(nil),    // 6: lock.v1.DeleteLockResponse
	(*v1.User)(nil),               // 7: user.v1.User
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_lock_v1_lock_proto_depIdxs = []int32{
	7, // 0: lock.v1.Lock.owner:type_name -> user.v1.User
	8, // 1: lock.v1.Lock.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: lock.v1.Lock.expires_at:type_name -> google.protobuf.Timestamp
	7, // 3: lock.v1.CreateLockRequest.owner:type_name -> user.v1.User
	0, // 4: lock.v1.CreateLockResponse.lock:type_name -> lock.v1.Lock
	0, // 5: lock.v1.GetLockResponse.lock:type_name -> lock.v1.Lock
	1, // 6: lock.v1.LockService.CreateLock:input_type -> lock.v1.CreateLockRequest
	3, // 7: lock.v1.LockService.GetLock:input_type -> lock.v1.GetLockRequest
	5, // 8: lock.v1.LockService.DeleteLock:input_type -> lock.v1.DeleteLockRequest
	2, // 9: lock.v1.LockService.CreateLock:output_type -> lock.v1.CreateLockResponse
	4, // 10: lock.v1.LockService.GetLock:output_type -> lock.v1.GetLockResponse
	6, // 11: lock.v1.LockService.DeleteLock:output_type -> lock.v1.DeleteLockResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_lock_v1_lock_proto_init() }
func file_lock_v1_lock_proto_init() {
	if File_lock_v1_lock_proto != nil {
		return
	}
	file_lock_v1_lock_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lock_v1_lock_proto_rawDesc), len(file_lock_v1_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lock_v1_lock_proto_goTypes,
		DependencyIndexes: file_lock_v1_lock_proto_depIdxs,
		MessageInfos:      file_lock_v1_lock_proto_msgTypes,
	}.Build()
	File_lock_v1_lock_proto = out.File
	file_lock_v1_lock_proto_goTypes = nil
	file_lock_v1_lock_proto_depIdxs = nil
}
