// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lock/v1/lock.proto

package lockv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/lock/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LockServiceName is the fully-qualified name of the LockService service.
	LockServiceName = "lock.v1.LockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LockServiceCreateLockProcedure is the fully-qualified name of the LockService's CreateLock RPC.
	LockServiceCreateLockProcedure = "/lock.v1.LockService/CreateLock"
	// LockServiceGetLockProcedure is the fully-qualified name of the LockService's GetLock RPC.
	LockServiceGetLockProcedure = "/lock.v1.LockService/GetLock"
	// LockServiceDeleteLockProcedure is the fully-qualified name of the LockService's DeleteLock RPC.
	LockServiceDeleteLockProcedure = "/lock.v1.LockService/DeleteLock"
)

// LockServiceClient is a client for the lock.v1.LockService service.
type LockServiceClient interface {
	CreateLock(context.Context, *connect.Request[v1.CreateLockRequest]) (*connect.Response[v1.CreateLockResponse], error)
	GetLock(context.Context, *connect.Request[v1.GetLockRequest]) (*connect.Response[v1.GetLockResponse], error)
	DeleteLock(context.Context, *connect.Request[v1.DeleteLockRequest]) (*connect.Response[v1.DeleteLockResponse], error)
}

// NewLockServiceClient constructs a client for the lock.v1.LockService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLockServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lockServiceMethods := v1.File_lock_v1_lock_proto.Services().ByName("LockService").Methods()
	return &lockServiceClient{
		createLock: connect.NewClient[v1.CreateLockRequest, v1.CreateLockResponse](
			httpClient,
			baseURL+LockServiceCreateLockProcedure,
			connect.WithSchema(lockServiceMethods.ByName("CreateLock")),
			connect.WithClientOptions(opts...),
		),
		getLock: connect.NewClient[v1.GetLockRequest, v1.GetLockResponse](
			httpClient,
			baseURL+LockServiceGetLockProcedure,
			connect.WithSchema(lockServiceMethods.ByName("GetLock")),
			connect.WithClientOptions(opts...),
		),
		deleteLock: connect.NewClient[v1.DeleteLockRequest, v1.DeleteLockResponse](
			httpClient,
			baseURL+LockServiceDeleteLockProcedure,
			connect.WithSchema(lockServiceMethods.ByName("DeleteLock")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lockServiceClient implements LockServiceClient.
type lockServiceClient struct {
	createLock *connect.Client[v1.CreateLockRequest, v1.CreateLockResponse]
	getLock    *connect.Client[v1.GetLockRequest, v1.GetLockResponse]
	deleteLock *connect.Client[v1.DeleteLockRequest, v1.DeleteLockResponse]
}

// CreateLock calls lock.v1.LockService.CreateLock.
func (c *lockServiceClient) CreateLock(ctx context.Context, req *connect.Request[v1.CreateLockRequest]) (*connect.Response[v1.CreateLockResponse], error) {
	return c.createLock.CallUnary(ctx, req)
}

// GetLock calls lock.v1.LockService.GetLock.
func (c *lockServiceClient) GetLock(ctx context.Context, req *connect.Request[v1.GetLockRequest]) (*connect.Response[v1.GetLockResponse], error) {
	return c.getLock.CallUnary(ctx, req)
}

// DeleteLock calls lock.v1.LockService.DeleteLock.
func (c *lockServiceClient) DeleteLock(ctx context.Context, req *connect.Request[v1.DeleteLockRequest]) (*connect.Response[v1.DeleteLockResponse], error) {
	return c.deleteLock.CallUnary(ctx, req)
}

// LockServiceHandler is an implementation of the lock.v1.LockService service.
type LockServiceHandler interface {
	CreateLock(context.Context, *connect.Request[v1.CreateLockRequest]) (*connect.Response[v1.CreateLockResponse], error)
	GetLock(context.Context, *connect.Request[v1.GetLockRequest]) (*connect.Response[v1.GetLockResponse], error)
	DeleteLock(context.Context, *connect.Request[v1.DeleteLockRequest]) (*connect.Response[v1.DeleteLockResponse], error)
}

// NewLockServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLockServiceHandler(svc LockServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lockServiceMethods := v1.File_lock_v1_lock_proto.Services().ByName("LockService").Methods()
	lockServiceCreateLockHandler := connect.NewUnaryHandler(
		LockServiceCreateLockProcedure,
		svc.CreateLock,
		connect.WithSchema(lockServiceMethods.ByName("CreateLock")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceGetLockHandler := connect.NewUnaryHandler(
		LockServiceGetLockProcedure,
		svc.GetLock,
		connect.WithSchema(lockServiceMethods.ByName("GetLock")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceDeleteLockHandler := connect.NewUnaryHandler(
		LockServiceDeleteLockProcedure,
		svc.DeleteLock,
		connect.WithSchema(lockServiceMethods.ByName("DeleteLock")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lock.v1.LockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LockServiceCreateLockProcedure:
			lockServiceCreateLockHandler.ServeHTTP(w, r)
		case LockServiceGetLockProcedure:
			lockServiceGetLockHandler.ServeHTTP(w, r)
		case LockServiceDeleteLockProcedure:
			lockServiceDeleteLockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLockServiceHandler struct{}

func (UnimplementedLockServiceHandler) CreateLock(context.Context, *connect.Request[v1.CreateLockRequest]) (*connect.Response[v1.CreateLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.CreateLock is not implemented"))
}

func (UnimplementedLockServiceHandler) GetLock(context.Context, *connect.Request[v1.GetLockRequest]) (*connect.Response[v1.GetLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.GetLock is not implemented"))
}

func (UnimplementedLockServiceHandler) DeleteLock(context.Context, *connect.Request[v1.DeleteLockRequest]) (*connect.Response[v1.DeleteLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.DeleteLock is not implemented"))
}
