// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: user_membership/v1/user_membership.proto

package userMembershipv1

import (
	_ "github.com/terrabase-dev/terrabase-sdk/specs/authz/v1"
	v11 "github.com/terrabase-dev/terrabase-sdk/specs/operation/v1"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/user_role/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a user who has access to an organization
type OrganizationUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the organization user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the user that has access to the organization
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the organization the user has access to
	OrganizationId string `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The role granted to the user in the organization
	UserRole v1.UserRole `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	// The time the user was granted access to the organization
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who granted the user access to the organization
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the user's access in the organization was last changed
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last changed the user's access in the organization
	UpdatedBy     string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationUser) Reset() {
	*x = OrganizationUser{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationUser) ProtoMessage() {}

func (x *OrganizationUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationUser.ProtoReflect.Descriptor instead.
func (*OrganizationUser) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationUser) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationUser) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

func (x *OrganizationUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrganizationUser) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *OrganizationUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OrganizationUser) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type AddUserToOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's first name
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// The user's last name
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// The user's email address
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The user's password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// The role the user should be granted in the organization
	UserRole v1.UserRole `protobuf:"varint,5,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	// The ID of the organization to add the user to
	OrganizationId string `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddUserToOrganizationRequest) Reset() {
	*x = AddUserToOrganizationRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToOrganizationRequest) ProtoMessage() {}

func (x *AddUserToOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToOrganizationRequest.ProtoReflect.Descriptor instead.
func (*AddUserToOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserToOrganizationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddUserToOrganizationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AddUserToOrganizationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddUserToOrganizationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddUserToOrganizationRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

func (x *AddUserToOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type AddUserToOrganizationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationUser *OrganizationUser      `protobuf:"bytes,1,opt,name=organization_user,json=organizationUser,proto3" json:"organization_user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddUserToOrganizationResponse) Reset() {
	*x = AddUserToOrganizationResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToOrganizationResponse) ProtoMessage() {}

func (x *AddUserToOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToOrganizationResponse.ProtoReflect.Descriptor instead.
func (*AddUserToOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{2}
}

func (x *AddUserToOrganizationResponse) GetOrganizationUser() *OrganizationUser {
	if x != nil {
		return x.OrganizationUser
	}
	return nil
}

type RemoveUserFromOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user to remove from the organization
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the organization to remove the user from
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveUserFromOrganizationRequest) Reset() {
	*x = RemoveUserFromOrganizationRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromOrganizationRequest) ProtoMessage() {}

func (x *RemoveUserFromOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromOrganizationRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveUserFromOrganizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveUserFromOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type RemoveUserFromOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromOrganizationResponse) Reset() {
	*x = RemoveUserFromOrganizationResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromOrganizationResponse) ProtoMessage() {}

func (x *RemoveUserFromOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromOrganizationResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{4}
}

type SetUserOrganizationRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user whose role should in the organization should be set
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the organization to set the user's role in
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The role to grant to the user
	UserRole      v1.UserRole `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserOrganizationRoleRequest) Reset() {
	*x = SetUserOrganizationRoleRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserOrganizationRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserOrganizationRoleRequest) ProtoMessage() {}

func (x *SetUserOrganizationRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserOrganizationRoleRequest.ProtoReflect.Descriptor instead.
func (*SetUserOrganizationRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{5}
}

func (x *SetUserOrganizationRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserOrganizationRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetUserOrganizationRoleRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

type SetUserOrganizationRoleResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationUser *OrganizationUser      `protobuf:"bytes,1,opt,name=organization_user,json=organizationUser,proto3" json:"organization_user,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetUserOrganizationRoleResponse) Reset() {
	*x = SetUserOrganizationRoleResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserOrganizationRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserOrganizationRoleResponse) ProtoMessage() {}

func (x *SetUserOrganizationRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserOrganizationRoleResponse.ProtoReflect.Descriptor instead.
func (*SetUserOrganizationRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{6}
}

func (x *SetUserOrganizationRoleResponse) GetOrganizationUser() *OrganizationUser {
	if x != nil {
		return x.OrganizationUser
	}
	return nil
}

// Defines a user who has access to a team
type TeamUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the user that has access to the team
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the team the user has access to
	TeamId string `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The role granted to the user in the team
	UserRole v1.UserRole `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	// The time the user was granted access to the team
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who granted the user access to the team
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the user's access in the team was last changed
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last changed the user's access in the team
	UpdatedBy     string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamUser) Reset() {
	*x = TeamUser{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamUser) ProtoMessage() {}

func (x *TeamUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamUser.ProtoReflect.Descriptor instead.
func (*TeamUser) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{7}
}

func (x *TeamUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamUser) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamUser) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

func (x *TeamUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamUser) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TeamUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TeamUser) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type AddUserToTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user to add to the team
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the team to add the user to
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The role the user should be granted in the team
	UserRole      v1.UserRole `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToTeamRequest) Reset() {
	*x = AddUserToTeamRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToTeamRequest) ProtoMessage() {}

func (x *AddUserToTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToTeamRequest.ProtoReflect.Descriptor instead.
func (*AddUserToTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{8}
}

func (x *AddUserToTeamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserToTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddUserToTeamRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

type AddUserToTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamUser      *TeamUser              `protobuf:"bytes,1,opt,name=team_user,json=teamUser,proto3" json:"team_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToTeamResponse) Reset() {
	*x = AddUserToTeamResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToTeamResponse) ProtoMessage() {}

func (x *AddUserToTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToTeamResponse.ProtoReflect.Descriptor instead.
func (*AddUserToTeamResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{9}
}

func (x *AddUserToTeamResponse) GetTeamUser() *TeamUser {
	if x != nil {
		return x.TeamUser
	}
	return nil
}

type RemoveUserFromTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user to remove from the team
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the team to remove the user from
	TeamId        string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTeamRequest) Reset() {
	*x = RemoveUserFromTeamRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTeamRequest) ProtoMessage() {}

func (x *RemoveUserFromTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTeamRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTeamRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveUserFromTeamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveUserFromTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type RemoveUserFromTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTeamResponse) Reset() {
	*x = RemoveUserFromTeamResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTeamResponse) ProtoMessage() {}

func (x *RemoveUserFromTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTeamResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTeamResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{11}
}

type SetUserTeamRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user whose role should in the team should be set
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the team to set the user's role in
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The role to grant to the user
	UserRole      v1.UserRole `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserTeamRoleRequest) Reset() {
	*x = SetUserTeamRoleRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserTeamRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTeamRoleRequest) ProtoMessage() {}

func (x *SetUserTeamRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTeamRoleRequest.ProtoReflect.Descriptor instead.
func (*SetUserTeamRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserTeamRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserTeamRoleRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SetUserTeamRoleRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

type SetUserTeamRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamUser      *TeamUser              `protobuf:"bytes,1,opt,name=team_user,json=teamUser,proto3" json:"team_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserTeamRoleResponse) Reset() {
	*x = SetUserTeamRoleResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserTeamRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTeamRoleResponse) ProtoMessage() {}

func (x *SetUserTeamRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTeamRoleResponse.ProtoReflect.Descriptor instead.
func (*SetUserTeamRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserTeamRoleResponse) GetTeamUser() *TeamUser {
	if x != nil {
		return x.TeamUser
	}
	return nil
}

// Defines a user who has access to a workspace
type WorkspaceUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the workspace user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the user that has access to the workspace
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the workspace the user has access to
	WorkspaceId string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The role granted to the user in the workspace
	UserRole v1.UserRole `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	// The Terraform operations the user is allowed to perform on a workspace
	AllowedOperations []v11.TerraformOperation `protobuf:"varint,5,rep,packed,name=allowed_operations,json=allowedOperations,proto3,enum=operation.v1.TerraformOperation" json:"allowed_operations,omitempty"`
	// The time the user was granted access to the workspace
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who granted the user access to the workspace
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the user's access in the workspace was last changed
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last changed the user's access in the workspace
	UpdatedBy     string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceUser) Reset() {
	*x = WorkspaceUser{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceUser) ProtoMessage() {}

func (x *WorkspaceUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceUser.ProtoReflect.Descriptor instead.
func (*WorkspaceUser) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{14}
}

func (x *WorkspaceUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkspaceUser) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceUser) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

func (x *WorkspaceUser) GetAllowedOperations() []v11.TerraformOperation {
	if x != nil {
		return x.AllowedOperations
	}
	return nil
}

func (x *WorkspaceUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkspaceUser) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *WorkspaceUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WorkspaceUser) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type AddUserToWorkspaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user to add to the workspace
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the workspace to add the user to
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The role the user should be granted in the workspace
	UserRole v1.UserRole `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	// The Terraform operations the user is allowed to perform on a workspace
	AllowedOperations []v11.TerraformOperation `protobuf:"varint,4,rep,packed,name=allowed_operations,json=allowedOperations,proto3,enum=operation.v1.TerraformOperation" json:"allowed_operations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddUserToWorkspaceRequest) Reset() {
	*x = AddUserToWorkspaceRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToWorkspaceRequest) ProtoMessage() {}

func (x *AddUserToWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*AddUserToWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{15}
}

func (x *AddUserToWorkspaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserToWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AddUserToWorkspaceRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

func (x *AddUserToWorkspaceRequest) GetAllowedOperations() []v11.TerraformOperation {
	if x != nil {
		return x.AllowedOperations
	}
	return nil
}

type AddUserToWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceUser *WorkspaceUser         `protobuf:"bytes,1,opt,name=workspace_user,json=workspaceUser,proto3" json:"workspace_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToWorkspaceResponse) Reset() {
	*x = AddUserToWorkspaceResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToWorkspaceResponse) ProtoMessage() {}

func (x *AddUserToWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*AddUserToWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{16}
}

func (x *AddUserToWorkspaceResponse) GetWorkspaceUser() *WorkspaceUser {
	if x != nil {
		return x.WorkspaceUser
	}
	return nil
}

type RemoveUserFromWorkspaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user to remove from the workspace
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the workspace to remove the user from
	WorkspaceId   string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromWorkspaceRequest) Reset() {
	*x = RemoveUserFromWorkspaceRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromWorkspaceRequest) ProtoMessage() {}

func (x *RemoveUserFromWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveUserFromWorkspaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveUserFromWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type RemoveUserFromWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromWorkspaceResponse) Reset() {
	*x = RemoveUserFromWorkspaceResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromWorkspaceResponse) ProtoMessage() {}

func (x *RemoveUserFromWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{18}
}

type SetUserWorkspaceRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user whose role should in the workspace should be set
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the workspace to set the user's role in
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The role to grant to the user
	UserRole      v1.UserRole `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_role.v1.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserWorkspaceRoleRequest) Reset() {
	*x = SetUserWorkspaceRoleRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserWorkspaceRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserWorkspaceRoleRequest) ProtoMessage() {}

func (x *SetUserWorkspaceRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserWorkspaceRoleRequest.ProtoReflect.Descriptor instead.
func (*SetUserWorkspaceRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{19}
}

func (x *SetUserWorkspaceRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserWorkspaceRoleRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SetUserWorkspaceRoleRequest) GetUserRole() v1.UserRole {
	if x != nil {
		return x.UserRole
	}
	return v1.UserRole(0)
}

type SetUserWorkspaceRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceUser *WorkspaceUser         `protobuf:"bytes,1,opt,name=workspace_user,json=workspaceUser,proto3" json:"workspace_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserWorkspaceRoleResponse) Reset() {
	*x = SetUserWorkspaceRoleResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserWorkspaceRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserWorkspaceRoleResponse) ProtoMessage() {}

func (x *SetUserWorkspaceRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserWorkspaceRoleResponse.ProtoReflect.Descriptor instead.
func (*SetUserWorkspaceRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{20}
}

func (x *SetUserWorkspaceRoleResponse) GetWorkspaceUser() *WorkspaceUser {
	if x != nil {
		return x.WorkspaceUser
	}
	return nil
}

type SetUserWorkspaceAllowedOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the user whose allowed Terraform operations should be set
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The ID of the workspace to set the user's allowed Terraform operations in
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The Terraform operations to allow the user to perform
	AllowedOperations []v11.TerraformOperation `protobuf:"varint,3,rep,packed,name=allowed_operations,json=allowedOperations,proto3,enum=operation.v1.TerraformOperation" json:"allowed_operations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetUserWorkspaceAllowedOperationsRequest) Reset() {
	*x = SetUserWorkspaceAllowedOperationsRequest{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserWorkspaceAllowedOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserWorkspaceAllowedOperationsRequest) ProtoMessage() {}

func (x *SetUserWorkspaceAllowedOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserWorkspaceAllowedOperationsRequest.ProtoReflect.Descriptor instead.
func (*SetUserWorkspaceAllowedOperationsRequest) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{21}
}

func (x *SetUserWorkspaceAllowedOperationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserWorkspaceAllowedOperationsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SetUserWorkspaceAllowedOperationsRequest) GetAllowedOperations() []v11.TerraformOperation {
	if x != nil {
		return x.AllowedOperations
	}
	return nil
}

type SetUserWorkspaceAllowedOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceUser *WorkspaceUser         `protobuf:"bytes,1,opt,name=workspace_user,json=workspaceUser,proto3" json:"workspace_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserWorkspaceAllowedOperationsResponse) Reset() {
	*x = SetUserWorkspaceAllowedOperationsResponse{}
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserWorkspaceAllowedOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserWorkspaceAllowedOperationsResponse) ProtoMessage() {}

func (x *SetUserWorkspaceAllowedOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_membership_v1_user_membership_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserWorkspaceAllowedOperationsResponse.ProtoReflect.Descriptor instead.
func (*SetUserWorkspaceAllowedOperationsResponse) Descriptor() ([]byte, []int) {
	return file_user_membership_v1_user_membership_proto_rawDescGZIP(), []int{22}
}

func (x *SetUserWorkspaceAllowedOperationsResponse) GetWorkspaceUser() *WorkspaceUser {
	if x != nil {
		return x.WorkspaceUser
	}
	return nil
}

var File_user_membership_v1_user_membership_proto protoreflect.FileDescriptor

const file_user_membership_v1_user_membership_proto_rawDesc = "" +
	"\n" +
	"(user_membership/v1/user_membership.proto\x12\x12user_membership.v1\x1a\x14authz/v1/authz.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1coperation/v1/operation.proto\x1a\x1cuser_role/v1/user_role.proto\"\xcd\x02\n" +
	"\x10OrganizationUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x123\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\x16.user_role.v1.UserRoleR\buserRole\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\x88\x02\n" +
	"\x1cAddUserToOrganizationRequest\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\x03\xe0A\x02R\tfirstName\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tB\x03\xe0A\x02R\blastName\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tB\x03\xe0A\x02R\x05email\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tB\x03\xe0A\x02R\bpassword\x128\n" +
	"\tuser_role\x18\x05 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\x12,\n" +
	"\x0forganization_id\x18\x06 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\"r\n" +
	"\x1dAddUserToOrganizationResponse\x12Q\n" +
	"\x11organization_user\x18\x01 \x01(\v2$.user_membership.v1.OrganizationUserR\x10organizationUser\"o\n" +
	"!RemoveUserFromOrganizationRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\"$\n" +
	"\"RemoveUserFromOrganizationResponse\"\xa6\x01\n" +
	"\x1eSetUserOrganizationRoleRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\x128\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\"t\n" +
	"\x1fSetUserOrganizationRoleResponse\x12Q\n" +
	"\x11organization_user\x18\x01 \x01(\v2$.user_membership.v1.OrganizationUserR\x10organizationUser\"\xb5\x02\n" +
	"\bTeamUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x123\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\x16.user_role.v1.UserRoleR\buserRole\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\x8c\x01\n" +
	"\x14AddUserToTeamRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06teamId\x128\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\"R\n" +
	"\x15AddUserToTeamResponse\x129\n" +
	"\tteam_user\x18\x01 \x01(\v2\x1c.user_membership.v1.TeamUserR\bteamUser\"W\n" +
	"\x19RemoveUserFromTeamRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06teamId\"\x1c\n" +
	"\x1aRemoveUserFromTeamResponse\"\x8e\x01\n" +
	"\x16SetUserTeamRoleRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06teamId\x128\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\"T\n" +
	"\x17SetUserTeamRoleResponse\x129\n" +
	"\tteam_user\x18\x01 \x01(\v2\x1c.user_membership.v1.TeamUserR\bteamUser\"\x95\x03\n" +
	"\rWorkspaceUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x123\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\x16.user_role.v1.UserRoleR\buserRole\x12O\n" +
	"\x12allowed_operations\x18\x05 \x03(\x0e2 .operation.v1.TerraformOperationR\x11allowedOperations\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\"\xf1\x01\n" +
	"\x19AddUserToWorkspaceRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x128\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\x12T\n" +
	"\x12allowed_operations\x18\x04 \x03(\x0e2 .operation.v1.TerraformOperationB\x03\xe0A\x02R\x11allowedOperations\"f\n" +
	"\x1aAddUserToWorkspaceResponse\x12H\n" +
	"\x0eworkspace_user\x18\x01 \x01(\v2!.user_membership.v1.WorkspaceUserR\rworkspaceUser\"f\n" +
	"\x1eRemoveUserFromWorkspaceRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\"!\n" +
	"\x1fRemoveUserFromWorkspaceResponse\"\x9d\x01\n" +
	"\x1bSetUserWorkspaceRoleRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x128\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x16.user_role.v1.UserRoleB\x03\xe0A\x02R\buserRole\"h\n" +
	"\x1cSetUserWorkspaceRoleResponse\x12H\n" +
	"\x0eworkspace_user\x18\x01 \x01(\v2!.user_membership.v1.WorkspaceUserR\rworkspaceUser\"\xc6\x01\n" +
	"(SetUserWorkspaceAllowedOperationsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06userId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12T\n" +
	"\x12allowed_operations\x18\x03 \x03(\x0e2 .operation.v1.TerraformOperationB\x03\xe0A\x02R\x11allowedOperations\"u\n" +
	")SetUserWorkspaceAllowedOperationsResponse\x12H\n" +
	"\x0eworkspace_user\x18\x01 \x01(\v2!.user_membership.v1.WorkspaceUserR\rworkspaceUser2\x81\v\n" +
	"\x15UserMembershipService\x12\x88\x01\n" +
	"\x15AddUserToOrganization\x120.user_membership.v1.AddUserToOrganizationRequest\x1a1.user_membership.v1.AddUserToOrganizationResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x12\x97\x01\n" +
	"\x1aRemoveUserFromOrganization\x125.user_membership.v1.RemoveUserFromOrganizationRequest\x1a6.user_membership.v1.RemoveUserFromOrganizationResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x12\x8e\x01\n" +
	"\x17SetUserOrganizationRole\x122.user_membership.v1.SetUserOrganizationRoleRequest\x1a3.user_membership.v1.SetUserOrganizationRoleResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x12p\n" +
	"\rAddUserToTeam\x12(.user_membership.v1.AddUserToTeamRequest\x1a).user_membership.v1.AddUserToTeamResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\x12\x7f\n" +
	"\x12RemoveUserFromTeam\x12-.user_membership.v1.RemoveUserFromTeamRequest\x1a..user_membership.v1.RemoveUserFromTeamResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\x12v\n" +
	"\x0fSetUserTeamRole\x12*.user_membership.v1.SetUserTeamRoleRequest\x1a+.user_membership.v1.SetUserTeamRoleResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\x12\x7f\n" +
	"\x12AddUserToWorkspace\x12-.user_membership.v1.AddUserToWorkspaceRequest\x1a..user_membership.v1.AddUserToWorkspaceResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\n" +
	"\x12\x8e\x01\n" +
	"\x17RemoveUserFromWorkspace\x122.user_membership.v1.RemoveUserFromWorkspaceRequest\x1a3.user_membership.v1.RemoveUserFromWorkspaceResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\n" +
	"\x12\x85\x01\n" +
	"\x14SetUserWorkspaceRole\x12/.user_membership.v1.SetUserWorkspaceRoleRequest\x1a0.user_membership.v1.SetUserWorkspaceRoleResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\n" +
	"\x12\xac\x01\n" +
	"!SetUserWorkspaceAllowedOperations\x12<.user_membership.v1.SetUserWorkspaceAllowedOperationsRequest\x1a=.user_membership.v1.SetUserWorkspaceAllowedOperationsResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\n" +
	"BRZPgithub.com/terrabase-dev/terrabase-sdk/specs/user_membership/v1;userMembershipv1b\x06proto3"

var (
	file_user_membership_v1_user_membership_proto_rawDescOnce sync.Once
	file_user_membership_v1_user_membership_proto_rawDescData []byte
)

func file_user_membership_v1_user_membership_proto_rawDescGZIP() []byte {
	file_user_membership_v1_user_membership_proto_rawDescOnce.Do(func() {
		file_user_membership_v1_user_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_membership_v1_user_membership_proto_rawDesc), len(file_user_membership_v1_user_membership_proto_rawDesc)))
	})
	return file_user_membership_v1_user_membership_proto_rawDescData
}

var file_user_membership_v1_user_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_user_membership_v1_user_membership_proto_goTypes = []any{
	(*OrganizationUser)(nil),                          // 0: user_membership.v1.OrganizationUser
	(*AddUserToOrganizationRequest)(nil),              // 1: user_membership.v1.AddUserToOrganizationRequest
	(*AddUserToOrganizationResponse)(nil),             // 2: user_membership.v1.AddUserToOrganizationResponse
	(*RemoveUserFromOrganizationRequest)(nil),         // 3: user_membership.v1.RemoveUserFromOrganizationRequest
	(*RemoveUserFromOrganizationResponse)(nil),        // 4: user_membership.v1.RemoveUserFromOrganizationResponse
	(*SetUserOrganizationRoleRequest)(nil),            // 5: user_membership.v1.SetUserOrganizationRoleRequest
	(*SetUserOrganizationRoleResponse)(nil),           // 6: user_membership.v1.SetUserOrganizationRoleResponse
	(*TeamUser)(nil),                                  // 7: user_membership.v1.TeamUser
	(*AddUserToTeamRequest)(nil),                      // 8: user_membership.v1.AddUserToTeamRequest
	(*AddUserToTeamResponse)(nil),                     // 9: user_membership.v1.AddUserToTeamResponse
	(*RemoveUserFromTeamRequest)(nil),                 // 10: user_membership.v1.RemoveUserFromTeamRequest
	(*RemoveUserFromTeamResponse)(nil),                // 11: user_membership.v1.RemoveUserFromTeamResponse
	(*SetUserTeamRoleRequest)(nil),                    // 12: user_membership.v1.SetUserTeamRoleRequest
	(*SetUserTeamRoleResponse)(nil),                   // 13: user_membership.v1.SetUserTeamRoleResponse
	(*WorkspaceUser)(nil),                             // 14: user_membership.v1.WorkspaceUser
	(*AddUserToWorkspaceRequest)(nil),                 // 15: user_membership.v1.AddUserToWorkspaceRequest
	(*AddUserToWorkspaceResponse)(nil),                // 16: user_membership.v1.AddUserToWorkspaceResponse
	(*RemoveUserFromWorkspaceRequest)(nil),            // 17: user_membership.v1.RemoveUserFromWorkspaceRequest
	(*RemoveUserFromWorkspaceResponse)(nil),           // 18: user_membership.v1.RemoveUserFromWorkspaceResponse
	(*SetUserWorkspaceRoleRequest)(nil),               // 19: user_membership.v1.SetUserWorkspaceRoleRequest
	(*SetUserWorkspaceRoleResponse)(nil),              // 20: user_membership.v1.SetUserWorkspaceRoleResponse
	(*SetUserWorkspaceAllowedOperationsRequest)(nil),  // 21: user_membership.v1.SetUserWorkspaceAllowedOperationsRequest
	(*SetUserWorkspaceAllowedOperationsResponse)(nil), // 22: user_membership.v1.SetUserWorkspaceAllowedOperationsResponse
	(v1.UserRole)(0),                                  // 23: user_role.v1.UserRole
	(*timestamppb.Timestamp)(nil),                     // 24: google.protobuf.Timestamp
	(v11.TerraformOperation)(0),                       // 25: operation.v1.TerraformOperation
}
var file_user_membership_v1_user_membership_proto_depIdxs = []int32{
	23, // 0: user_membership.v1.OrganizationUser.user_role:type_name -> user_role.v1.UserRole
	24, // 1: user_membership.v1.OrganizationUser.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: user_membership.v1.OrganizationUser.updated_at:type_name -> google.protobuf.Timestamp
	23, // 3: user_membership.v1.AddUserToOrganizationRequest.user_role:type_name -> user_role.v1.UserRole
	0,  // 4: user_membership.v1.AddUserToOrganizationResponse.organization_user:type_name -> user_membership.v1.OrganizationUser
	23, // 5: user_membership.v1.SetUserOrganizationRoleRequest.user_role:type_name -> user_role.v1.UserRole
	0,  // 6: user_membership.v1.SetUserOrganizationRoleResponse.organization_user:type_name -> user_membership.v1.OrganizationUser
	23, // 7: user_membership.v1.TeamUser.user_role:type_name -> user_role.v1.UserRole
	24, // 8: user_membership.v1.TeamUser.created_at:type_name -> google.protobuf.Timestamp
	24, // 9: user_membership.v1.TeamUser.updated_at:type_name -> google.protobuf.Timestamp
	23, // 10: user_membership.v1.AddUserToTeamRequest.user_role:type_name -> user_role.v1.UserRole
	7,  // 11: user_membership.v1.AddUserToTeamResponse.team_user:type_name -> user_membership.v1.TeamUser
	23, // 12: user_membership.v1.SetUserTeamRoleRequest.user_role:type_name -> user_role.v1.UserRole
	7,  // 13: user_membership.v1.SetUserTeamRoleResponse.team_user:type_name -> user_membership.v1.TeamUser
	23, // 14: user_membership.v1.WorkspaceUser.user_role:type_name -> user_role.v1.UserRole
	25, // 15: user_membership.v1.WorkspaceUser.allowed_operations:type_name -> operation.v1.TerraformOperation
	24, // 16: user_membership.v1.WorkspaceUser.created_at:type_name -> google.protobuf.Timestamp
	24, // 17: user_membership.v1.WorkspaceUser.updated_at:type_name -> google.protobuf.Timestamp
	23, // 18: user_membership.v1.AddUserToWorkspaceRequest.user_role:type_name -> user_role.v1.UserRole
	25, // 19: user_membership.v1.AddUserToWorkspaceRequest.allowed_operations:type_name -> operation.v1.TerraformOperation
	14, // 20: user_membership.v1.AddUserToWorkspaceResponse.workspace_user:type_name -> user_membership.v1.WorkspaceUser
	23, // 21: user_membership.v1.SetUserWorkspaceRoleRequest.user_role:type_name -> user_role.v1.UserRole
	14, // 22: user_membership.v1.SetUserWorkspaceRoleResponse.workspace_user:type_name -> user_membership.v1.WorkspaceUser
	25, // 23: user_membership.v1.SetUserWorkspaceAllowedOperationsRequest.allowed_operations:type_name -> operation.v1.TerraformOperation
	14, // 24: user_membership.v1.SetUserWorkspaceAllowedOperationsResponse.workspace_user:type_name -> user_membership.v1.WorkspaceUser
	1,  // 25: user_membership.v1.UserMembershipService.AddUserToOrganization:input_type -> user_membership.v1.AddUserToOrganizationRequest
	3,  // 26: user_membership.v1.UserMembershipService.RemoveUserFromOrganization:input_type -> user_membership.v1.RemoveUserFromOrganizationRequest
	5,  // 27: user_membership.v1.UserMembershipService.SetUserOrganizationRole:input_type -> user_membership.v1.SetUserOrganizationRoleRequest
	8,  // 28: user_membership.v1.UserMembershipService.AddUserToTeam:input_type -> user_membership.v1.AddUserToTeamRequest
	10, // 29: user_membership.v1.UserMembershipService.RemoveUserFromTeam:input_type -> user_membership.v1.RemoveUserFromTeamRequest
	12, // 30: user_membership.v1.UserMembershipService.SetUserTeamRole:input_type -> user_membership.v1.SetUserTeamRoleRequest
	15, // 31: user_membership.v1.UserMembershipService.AddUserToWorkspace:input_type -> user_membership.v1.AddUserToWorkspaceRequest
	17, // 32: user_membership.v1.UserMembershipService.RemoveUserFromWorkspace:input_type -> user_membership.v1.RemoveUserFromWorkspaceRequest
	19, // 33: user_membership.v1.UserMembershipService.SetUserWorkspaceRole:input_type -> user_membership.v1.SetUserWorkspaceRoleRequest
	21, // 34: user_membership.v1.UserMembershipService.SetUserWorkspaceAllowedOperations:input_type -> user_membership.v1.SetUserWorkspaceAllowedOperationsRequest
	2,  // 35: user_membership.v1.UserMembershipService.AddUserToOrganization:output_type -> user_membership.v1.AddUserToOrganizationResponse
	4,  // 36: user_membership.v1.UserMembershipService.RemoveUserFromOrganization:output_type -> user_membership.v1.RemoveUserFromOrganizationResponse
	6,  // 37: user_membership.v1.UserMembershipService.SetUserOrganizationRole:output_type -> user_membership.v1.SetUserOrganizationRoleResponse
	9,  // 38: user_membership.v1.UserMembershipService.AddUserToTeam:output_type -> user_membership.v1.AddUserToTeamResponse
	11, // 39: user_membership.v1.UserMembershipService.RemoveUserFromTeam:output_type -> user_membership.v1.RemoveUserFromTeamResponse
	13, // 40: user_membership.v1.UserMembershipService.SetUserTeamRole:output_type -> user_membership.v1.SetUserTeamRoleResponse
	16, // 41: user_membership.v1.UserMembershipService.AddUserToWorkspace:output_type -> user_membership.v1.AddUserToWorkspaceResponse
	18, // 42: user_membership.v1.UserMembershipService.RemoveUserFromWorkspace:output_type -> user_membership.v1.RemoveUserFromWorkspaceResponse
	20, // 43: user_membership.v1.UserMembershipService.SetUserWorkspaceRole:output_type -> user_membership.v1.SetUserWorkspaceRoleResponse
	22, // 44: user_membership.v1.UserMembershipService.SetUserWorkspaceAllowedOperations:output_type -> user_membership.v1.SetUserWorkspaceAllowedOperationsResponse
	35, // [35:45] is the sub-list for method output_type
	25, // [25:35] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_user_membership_v1_user_membership_proto_init() }
func file_user_membership_v1_user_membership_proto_init() {
	if File_user_membership_v1_user_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_membership_v1_user_membership_proto_rawDesc), len(file_user_membership_v1_user_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_membership_v1_user_membership_proto_goTypes,
		DependencyIndexes: file_user_membership_v1_user_membership_proto_depIdxs,
		MessageInfos:      file_user_membership_v1_user_membership_proto_msgTypes,
	}.Build()
	File_user_membership_v1_user_membership_proto = out.File
	file_user_membership_v1_user_membership_proto_goTypes = nil
	file_user_membership_v1_user_membership_proto_depIdxs = nil
}
