// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drift_report/v1/drift_report.proto

package driftReportv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/drift_report/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DriftReportServiceName is the fully-qualified name of the DriftReportService service.
	DriftReportServiceName = "drift_report.v1.DriftReportService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DriftReportServiceCreateDriftReportProcedure is the fully-qualified name of the
	// DriftReportService's CreateDriftReport RPC.
	DriftReportServiceCreateDriftReportProcedure = "/drift_report.v1.DriftReportService/CreateDriftReport"
	// DriftReportServiceGetDriftReportProcedure is the fully-qualified name of the DriftReportService's
	// GetDriftReport RPC.
	DriftReportServiceGetDriftReportProcedure = "/drift_report.v1.DriftReportService/GetDriftReport"
)

// DriftReportServiceClient is a client for the drift_report.v1.DriftReportService service.
type DriftReportServiceClient interface {
	CreateDriftReport(context.Context, *connect.Request[v1.CreateDriftReportRequest]) (*connect.Response[v1.CreateDriftReportResponse], error)
	GetDriftReport(context.Context, *connect.Request[v1.GetDriftReportRequest]) (*connect.Response[v1.GetDriftReportResponse], error)
}

// NewDriftReportServiceClient constructs a client for the drift_report.v1.DriftReportService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDriftReportServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DriftReportServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	driftReportServiceMethods := v1.File_drift_report_v1_drift_report_proto.Services().ByName("DriftReportService").Methods()
	return &driftReportServiceClient{
		createDriftReport: connect.NewClient[v1.CreateDriftReportRequest, v1.CreateDriftReportResponse](
			httpClient,
			baseURL+DriftReportServiceCreateDriftReportProcedure,
			connect.WithSchema(driftReportServiceMethods.ByName("CreateDriftReport")),
			connect.WithClientOptions(opts...),
		),
		getDriftReport: connect.NewClient[v1.GetDriftReportRequest, v1.GetDriftReportResponse](
			httpClient,
			baseURL+DriftReportServiceGetDriftReportProcedure,
			connect.WithSchema(driftReportServiceMethods.ByName("GetDriftReport")),
			connect.WithClientOptions(opts...),
		),
	}
}

// driftReportServiceClient implements DriftReportServiceClient.
type driftReportServiceClient struct {
	createDriftReport *connect.Client[v1.CreateDriftReportRequest, v1.CreateDriftReportResponse]
	getDriftReport    *connect.Client[v1.GetDriftReportRequest, v1.GetDriftReportResponse]
}

// CreateDriftReport calls drift_report.v1.DriftReportService.CreateDriftReport.
func (c *driftReportServiceClient) CreateDriftReport(ctx context.Context, req *connect.Request[v1.CreateDriftReportRequest]) (*connect.Response[v1.CreateDriftReportResponse], error) {
	return c.createDriftReport.CallUnary(ctx, req)
}

// GetDriftReport calls drift_report.v1.DriftReportService.GetDriftReport.
func (c *driftReportServiceClient) GetDriftReport(ctx context.Context, req *connect.Request[v1.GetDriftReportRequest]) (*connect.Response[v1.GetDriftReportResponse], error) {
	return c.getDriftReport.CallUnary(ctx, req)
}

// DriftReportServiceHandler is an implementation of the drift_report.v1.DriftReportService service.
type DriftReportServiceHandler interface {
	CreateDriftReport(context.Context, *connect.Request[v1.CreateDriftReportRequest]) (*connect.Response[v1.CreateDriftReportResponse], error)
	GetDriftReport(context.Context, *connect.Request[v1.GetDriftReportRequest]) (*connect.Response[v1.GetDriftReportResponse], error)
}

// NewDriftReportServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDriftReportServiceHandler(svc DriftReportServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	driftReportServiceMethods := v1.File_drift_report_v1_drift_report_proto.Services().ByName("DriftReportService").Methods()
	driftReportServiceCreateDriftReportHandler := connect.NewUnaryHandler(
		DriftReportServiceCreateDriftReportProcedure,
		svc.CreateDriftReport,
		connect.WithSchema(driftReportServiceMethods.ByName("CreateDriftReport")),
		connect.WithHandlerOptions(opts...),
	)
	driftReportServiceGetDriftReportHandler := connect.NewUnaryHandler(
		DriftReportServiceGetDriftReportProcedure,
		svc.GetDriftReport,
		connect.WithSchema(driftReportServiceMethods.ByName("GetDriftReport")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drift_report.v1.DriftReportService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DriftReportServiceCreateDriftReportProcedure:
			driftReportServiceCreateDriftReportHandler.ServeHTTP(w, r)
		case DriftReportServiceGetDriftReportProcedure:
			driftReportServiceGetDriftReportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDriftReportServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDriftReportServiceHandler struct{}

func (UnimplementedDriftReportServiceHandler) CreateDriftReport(context.Context, *connect.Request[v1.CreateDriftReportRequest]) (*connect.Response[v1.CreateDriftReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drift_report.v1.DriftReportService.CreateDriftReport is not implemented"))
}

func (UnimplementedDriftReportServiceHandler) GetDriftReport(context.Context, *connect.Request[v1.GetDriftReportRequest]) (*connect.Response[v1.GetDriftReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drift_report.v1.DriftReportService.GetDriftReport is not implemented"))
}
