// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file drift_report/v1/drift_report.proto (package drift_report.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file drift_report/v1/drift_report.proto.
 */
export const file_drift_report_v1_drift_report: GenFile = /*@__PURE__*/
  fileDesc("CiJkcmlmdF9yZXBvcnQvdjEvZHJpZnRfcmVwb3J0LnByb3RvEg9kcmlmdF9yZXBvcnQudjEiggEKBURyaWZ0EhMKC3Jlc291cmNlX2lkGAEgASgJEjQKB2NoYW5nZXMYAiADKAsyIy5kcmlmdF9yZXBvcnQudjEuRHJpZnQuQ2hhbmdlc0VudHJ5Gi4KDENoYW5nZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIpoBCgtEcmlmdFJlcG9ydBIKCgJpZBgBIAEoCRIUCgx3b3Jrc3BhY2VfaWQYAiABKAkSDwoHZHJpZnRlZBgDIAEoCBInCgdjaGFuZ2VzGAQgAygLMhYuZHJpZnRfcmVwb3J0LnYxLkRyaWZ0Ei8KC2RldGVjdGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJ5ChhDcmVhdGVEcmlmdFJlcG9ydFJlcXVlc3QSGQoMd29ya3NwYWNlX2lkGAEgASgJQgPgQQISFAoHZHJpZnRlZBgCIAEoCEID4EECEiwKB2NoYW5nZXMYAyADKAsyFi5kcmlmdF9yZXBvcnQudjEuRHJpZnRCA+BBAiJPChlDcmVhdGVEcmlmdFJlcG9ydFJlc3BvbnNlEjIKDGRyaWZ0X3JlcG9ydBgBIAEoCzIcLmRyaWZ0X3JlcG9ydC52MS5EcmlmdFJlcG9ydCIoChVHZXREcmlmdFJlcG9ydFJlcXVlc3QSDwoCaWQYASABKAlCA+BBAiJMChZHZXREcmlmdFJlcG9ydFJlc3BvbnNlEjIKDGRyaWZ0X3JlcG9ydBgBIAEoCzIcLmRyaWZ0X3JlcG9ydC52MS5EcmlmdFJlcG9ydDLjAQoSRHJpZnRSZXBvcnRTZXJ2aWNlEmoKEUNyZWF0ZURyaWZ0UmVwb3J0EikuZHJpZnRfcmVwb3J0LnYxLkNyZWF0ZURyaWZ0UmVwb3J0UmVxdWVzdBoqLmRyaWZ0X3JlcG9ydC52MS5DcmVhdGVEcmlmdFJlcG9ydFJlc3BvbnNlEmEKDkdldERyaWZ0UmVwb3J0EiYuZHJpZnRfcmVwb3J0LnYxLkdldERyaWZ0UmVwb3J0UmVxdWVzdBonLmRyaWZ0X3JlcG9ydC52MS5HZXREcmlmdFJlcG9ydFJlc3BvbnNlQkxaSmdpdGh1Yi5jb20vdGVycmFiYXNlLWRldi90ZXJyYWJhc2Utc2RrL3NwZWNzL2RyaWZ0X3JlcG9ydC92MTtkcmlmdFJlcG9ydHYxYgZwcm90bzM", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * @generated from message drift_report.v1.Drift
 */
export type Drift = Message<"drift_report.v1.Drift"> & {
  /**
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * @generated from field: map<string, string> changes = 2;
   */
  changes: { [key: string]: string };
};

/**
 * Describes the message drift_report.v1.Drift.
 * Use `create(DriftSchema)` to create a new message.
 */
export const DriftSchema: GenMessage<Drift> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 0);

/**
 * @generated from message drift_report.v1.DriftReport
 */
export type DriftReport = Message<"drift_report.v1.DriftReport"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: bool drifted = 3;
   */
  drifted: boolean;

  /**
   * @generated from field: repeated drift_report.v1.Drift changes = 4;
   */
  changes: Drift[];

  /**
   * @generated from field: google.protobuf.Timestamp detected_at = 5;
   */
  detectedAt?: Timestamp;
};

/**
 * Describes the message drift_report.v1.DriftReport.
 * Use `create(DriftReportSchema)` to create a new message.
 */
export const DriftReportSchema: GenMessage<DriftReport> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 1);

/**
 * @generated from message drift_report.v1.CreateDriftReportRequest
 */
export type CreateDriftReportRequest = Message<"drift_report.v1.CreateDriftReportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: bool drifted = 2;
   */
  drifted: boolean;

  /**
   * @generated from field: repeated drift_report.v1.Drift changes = 3;
   */
  changes: Drift[];
};

/**
 * Describes the message drift_report.v1.CreateDriftReportRequest.
 * Use `create(CreateDriftReportRequestSchema)` to create a new message.
 */
export const CreateDriftReportRequestSchema: GenMessage<CreateDriftReportRequest> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 2);

/**
 * @generated from message drift_report.v1.CreateDriftReportResponse
 */
export type CreateDriftReportResponse = Message<"drift_report.v1.CreateDriftReportResponse"> & {
  /**
   * @generated from field: drift_report.v1.DriftReport drift_report = 1;
   */
  driftReport?: DriftReport;
};

/**
 * Describes the message drift_report.v1.CreateDriftReportResponse.
 * Use `create(CreateDriftReportResponseSchema)` to create a new message.
 */
export const CreateDriftReportResponseSchema: GenMessage<CreateDriftReportResponse> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 3);

/**
 * @generated from message drift_report.v1.GetDriftReportRequest
 */
export type GetDriftReportRequest = Message<"drift_report.v1.GetDriftReportRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message drift_report.v1.GetDriftReportRequest.
 * Use `create(GetDriftReportRequestSchema)` to create a new message.
 */
export const GetDriftReportRequestSchema: GenMessage<GetDriftReportRequest> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 4);

/**
 * @generated from message drift_report.v1.GetDriftReportResponse
 */
export type GetDriftReportResponse = Message<"drift_report.v1.GetDriftReportResponse"> & {
  /**
   * @generated from field: drift_report.v1.DriftReport drift_report = 1;
   */
  driftReport?: DriftReport;
};

/**
 * Describes the message drift_report.v1.GetDriftReportResponse.
 * Use `create(GetDriftReportResponseSchema)` to create a new message.
 */
export const GetDriftReportResponseSchema: GenMessage<GetDriftReportResponse> = /*@__PURE__*/
  messageDesc(file_drift_report_v1_drift_report, 5);

/**
 * @generated from service drift_report.v1.DriftReportService
 */
export const DriftReportService: GenService<{
  /**
   * @generated from rpc drift_report.v1.DriftReportService.CreateDriftReport
   */
  createDriftReport: {
    methodKind: "unary";
    input: typeof CreateDriftReportRequestSchema;
    output: typeof CreateDriftReportResponseSchema;
  },
  /**
   * @generated from rpc drift_report.v1.DriftReportService.GetDriftReport
   */
  getDriftReport: {
    methodKind: "unary";
    input: typeof GetDriftReportRequestSchema;
    output: typeof GetDriftReportResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_drift_report_v1_drift_report, 0);

