// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: team/v1/team.proto

package teamv1

import (
	_ "github.com/terrabase-dev/terrabase-sdk/specs/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Terrabase team belongs to a single organization, and can have many users. Teams should likely strongly correlate with actual business units
type Team struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the team
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The ID of the organization the team belongs to
	OrganizationId string `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The team's slug (used in URLs)
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// The version of the team's logo, if uploaded
	LogoVersion string `protobuf:"bytes,5,opt,name=logo_version,json=logoVersion,proto3" json:"logo_version,omitempty"`
	// The time the team was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who created the team
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the team was last updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last updated the team
	UpdatedBy     string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_team_v1_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Team) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Team) GetLogoVersion() string {
	if x != nil {
		return x.LogoVersion
	}
	return ""
}

func (x *Team) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Team) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Team) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Team) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type TeamIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of team IDs
	TeamIds       []string `protobuf:"bytes,1,rep,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamIds) Reset() {
	*x = TeamIds{}
	mi := &file_team_v1_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamIds) ProtoMessage() {}

func (x *TeamIds) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamIds.ProtoReflect.Descriptor instead.
func (*TeamIds) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{1}
}

func (x *TeamIds) GetTeamIds() []string {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type CreateTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the team
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ID of the organization the team belongs to
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The team's slug. A reasonable default will be generated if not provided.
	Slug          string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateTeamRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateTeamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team that was created
	Team          *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*GetTeamRequest_Id
	//	*GetTeamRequest_Slug
	Key           isGetTeamRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamRequest) GetKey() isGetTeamRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetTeamRequest) GetId() string {
	if x != nil {
		if x, ok := x.Key.(*GetTeamRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetTeamRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Key.(*GetTeamRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetTeamRequest_Key interface {
	isGetTeamRequest_Key()
}

type GetTeamRequest_Id struct {
	// The unique ID of the team
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetTeamRequest_Slug struct {
	// The team's slug
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetTeamRequest_Id) isGetTeamRequest_Key() {}

func (*GetTeamRequest_Slug) isGetTeamRequest_Key() {}

type GetTeamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team
	Team          *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type ListTeamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of teams on each page of results
	PageSize *int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// The token to retrieve the next page of results
	PageToken     *string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_team_v1_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{6}
}

func (x *ListTeamsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListTeamsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListTeamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of teams
	Teams []*Team `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	// The token to retrieve the next page of results
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_team_v1_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team to update
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new name of the team
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The new slug for the team
	Slug *string `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	// Used to remove a logo
	LogoVersion   *string `protobuf:"bytes,4,opt,name=logo_version,json=logoVersion,proto3,oneof" json:"logo_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeamRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTeamRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateTeamRequest) GetLogoVersion() string {
	if x != nil && x.LogoVersion != nil {
		return *x.LogoVersion
	}
	return ""
}

type UpdateTeamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated team
	Team          *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTeamRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{11}
}

type GetLogoUploadUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team to get a presigned URL for to upload its logo
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The content type of the logo
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoUploadUrlRequest) Reset() {
	*x = GetLogoUploadUrlRequest{}
	mi := &file_team_v1_team_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoUploadUrlRequest) ProtoMessage() {}

func (x *GetLogoUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetLogoUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{12}
}

func (x *GetLogoUploadUrlRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *GetLogoUploadUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetLogoUploadUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The presigned URL to upload a team's logo
	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	// Headers to include when calling the presigned URL
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The version of the logo (to be used in finalize)
	LogoVersion   string `protobuf:"bytes,3,opt,name=logo_version,json=logoVersion,proto3" json:"logo_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoUploadUrlResponse) Reset() {
	*x = GetLogoUploadUrlResponse{}
	mi := &file_team_v1_team_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoUploadUrlResponse) ProtoMessage() {}

func (x *GetLogoUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetLogoUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{13}
}

func (x *GetLogoUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetLogoUploadUrlResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GetLogoUploadUrlResponse) GetLogoVersion() string {
	if x != nil {
		return x.LogoVersion
	}
	return ""
}

type FinalizeLogoUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team to finalize the logo upload for
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The version of the logo
	LogoVersion   string `protobuf:"bytes,2,opt,name=logo_version,json=logoVersion,proto3" json:"logo_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeLogoUploadRequest) Reset() {
	*x = FinalizeLogoUploadRequest{}
	mi := &file_team_v1_team_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeLogoUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeLogoUploadRequest) ProtoMessage() {}

func (x *FinalizeLogoUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeLogoUploadRequest.ProtoReflect.Descriptor instead.
func (*FinalizeLogoUploadRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{14}
}

func (x *FinalizeLogoUploadRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *FinalizeLogoUploadRequest) GetLogoVersion() string {
	if x != nil {
		return x.LogoVersion
	}
	return ""
}

type FinalizeLogoUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team
	Team          *Team `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeLogoUploadResponse) Reset() {
	*x = FinalizeLogoUploadResponse{}
	mi := &file_team_v1_team_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeLogoUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeLogoUploadResponse) ProtoMessage() {}

func (x *FinalizeLogoUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeLogoUploadResponse.ProtoReflect.Descriptor instead.
func (*FinalizeLogoUploadResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{15}
}

func (x *FinalizeLogoUploadResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type GetLogoUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team to get a presigned URL for to download its logo
	TeamId        string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoUrlRequest) Reset() {
	*x = GetLogoUrlRequest{}
	mi := &file_team_v1_team_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoUrlRequest) ProtoMessage() {}

func (x *GetLogoUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoUrlRequest.ProtoReflect.Descriptor instead.
func (*GetLogoUrlRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{16}
}

func (x *GetLogoUrlRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetLogoUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The presigned URL to download a team's logo
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoUrlResponse) Reset() {
	*x = GetLogoUrlResponse{}
	mi := &file_team_v1_team_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoUrlResponse) ProtoMessage() {}

func (x *GetLogoUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoUrlResponse.ProtoReflect.Descriptor instead.
func (*GetLogoUrlResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{17}
}

func (x *GetLogoUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_team_v1_team_proto protoreflect.FileDescriptor

const file_team_v1_team_proto_rawDesc = "" +
	"\n" +
	"\x12team/v1/team.proto\x12\ateam.v1\x1a\x14authz/v1/authz.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x02\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12!\n" +
	"\flogo_version\x18\x05 \x01(\tR\vlogoVersion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\"$\n" +
	"\aTeamIds\x12\x19\n" +
	"\bteam_ids\x18\x01 \x03(\tR\ateamIds\"n\n" +
	"\x11CreateTeamRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12,\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"7\n" +
	"\x12CreateTeamResponse\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\"?\n" +
	"\x0eGetTeamRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\x05\n" +
	"\x03key\"4\n" +
	"\x0fGetTeamResponse\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\"u\n" +
	"\x10ListTeamsRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"y\n" +
	"\x11ListTeamsResponse\x12#\n" +
	"\x05teams\x18\x01 \x03(\v2\r.team.v1.TeamR\x05teams\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xa5\x01\n" +
	"\x11UpdateTeamRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12&\n" +
	"\flogo_version\x18\x04 \x01(\tH\x02R\vlogoVersion\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\x0f\n" +
	"\r_logo_version\"7\n" +
	"\x12UpdateTeamResponse\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\"(\n" +
	"\x11DeleteTeamRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x14\n" +
	"\x12DeleteTeamResponse\"_\n" +
	"\x17GetLogoUploadUrlRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12&\n" +
	"\fcontent_type\x18\x02 \x01(\tB\x03\xe0A\x02R\vcontentType\"\xe2\x01\n" +
	"\x18GetLogoUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12H\n" +
	"\aheaders\x18\x02 \x03(\v2..team.v1.GetLogoUploadUrlResponse.HeadersEntryR\aheaders\x12!\n" +
	"\flogo_version\x18\x03 \x01(\tR\vlogoVersion\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x19FinalizeLogoUploadRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12&\n" +
	"\flogo_version\x18\x02 \x01(\tB\x03\xe0A\x02R\vlogoVersion\"?\n" +
	"\x1aFinalizeLogoUploadResponse\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\"1\n" +
	"\x11GetLogoUrlRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\"&\n" +
	"\x12GetLogoUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xdd\x05\n" +
	"\vTeamService\x12U\n" +
	"\n" +
	"CreateTeam\x12\x1a.team.v1.CreateTeamRequest\x1a\x1b.team.v1.CreateTeamResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01\x12I\n" +
	"\aGetTeam\x12\x17.team.v1.GetTeamRequest\x1a\x18.team.v1.GetTeamResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x05\x04\x12O\n" +
	"\tListTeams\x12\x19.team.v1.ListTeamsRequest\x1a\x1a.team.v1.ListTeamsResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x05\x04\x12U\n" +
	"\n" +
	"UpdateTeam\x12\x1a.team.v1.UpdateTeamRequest\x1a\x1b.team.v1.UpdateTeamResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01\x12U\n" +
	"\n" +
	"DeleteTeam\x12\x1a.team.v1.DeleteTeamRequest\x1a\x1b.team.v1.DeleteTeamResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01\x12g\n" +
	"\x10GetLogoUploadUrl\x12 .team.v1.GetLogoUploadUrlRequest\x1a!.team.v1.GetLogoUploadUrlResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01\x12m\n" +
	"\x12FinalizeLogoUpload\x12\".team.v1.FinalizeLogoUploadRequest\x1a#.team.v1.FinalizeLogoUploadResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01\x12U\n" +
	"\n" +
	"GetLogoUrl\x12\x1a.team.v1.GetLogoUrlRequest\x1a\x1b.team.v1.GetLogoUrlResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x04\xa8\xb5\x18\x01B=Z;github.com/terrabase-dev/terrabase-sdk/specs/team/v1;teamv1b\x06proto3"

var (
	file_team_v1_team_proto_rawDescOnce sync.Once
	file_team_v1_team_proto_rawDescData []byte
)

func file_team_v1_team_proto_rawDescGZIP() []byte {
	file_team_v1_team_proto_rawDescOnce.Do(func() {
		file_team_v1_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_v1_team_proto_rawDesc), len(file_team_v1_team_proto_rawDesc)))
	})
	return file_team_v1_team_proto_rawDescData
}

var file_team_v1_team_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_team_v1_team_proto_goTypes = []any{
	(*Team)(nil),                       // 0: team.v1.Team
	(*TeamIds)(nil),                    // 1: team.v1.TeamIds
	(*CreateTeamRequest)(nil),          // 2: team.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),         // 3: team.v1.CreateTeamResponse
	(*GetTeamRequest)(nil),             // 4: team.v1.GetTeamRequest
	(*GetTeamResponse)(nil),            // 5: team.v1.GetTeamResponse
	(*ListTeamsRequest)(nil),           // 6: team.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),          // 7: team.v1.ListTeamsResponse
	(*UpdateTeamRequest)(nil),          // 8: team.v1.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),         // 9: team.v1.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),          // 10: team.v1.DeleteTeamRequest
	(*DeleteTeamResponse)(nil),         // 11: team.v1.DeleteTeamResponse
	(*GetLogoUploadUrlRequest)(nil),    // 12: team.v1.GetLogoUploadUrlRequest
	(*GetLogoUploadUrlResponse)(nil),   // 13: team.v1.GetLogoUploadUrlResponse
	(*FinalizeLogoUploadRequest)(nil),  // 14: team.v1.FinalizeLogoUploadRequest
	(*FinalizeLogoUploadResponse)(nil), // 15: team.v1.FinalizeLogoUploadResponse
	(*GetLogoUrlRequest)(nil),          // 16: team.v1.GetLogoUrlRequest
	(*GetLogoUrlResponse)(nil),         // 17: team.v1.GetLogoUrlResponse
	nil,                                // 18: team.v1.GetLogoUploadUrlResponse.HeadersEntry
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_team_v1_team_proto_depIdxs = []int32{
	19, // 0: team.v1.Team.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: team.v1.Team.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: team.v1.CreateTeamResponse.team:type_name -> team.v1.Team
	0,  // 3: team.v1.GetTeamResponse.team:type_name -> team.v1.Team
	0,  // 4: team.v1.ListTeamsResponse.teams:type_name -> team.v1.Team
	0,  // 5: team.v1.UpdateTeamResponse.team:type_name -> team.v1.Team
	18, // 6: team.v1.GetLogoUploadUrlResponse.headers:type_name -> team.v1.GetLogoUploadUrlResponse.HeadersEntry
	0,  // 7: team.v1.FinalizeLogoUploadResponse.team:type_name -> team.v1.Team
	2,  // 8: team.v1.TeamService.CreateTeam:input_type -> team.v1.CreateTeamRequest
	4,  // 9: team.v1.TeamService.GetTeam:input_type -> team.v1.GetTeamRequest
	6,  // 10: team.v1.TeamService.ListTeams:input_type -> team.v1.ListTeamsRequest
	8,  // 11: team.v1.TeamService.UpdateTeam:input_type -> team.v1.UpdateTeamRequest
	10, // 12: team.v1.TeamService.DeleteTeam:input_type -> team.v1.DeleteTeamRequest
	12, // 13: team.v1.TeamService.GetLogoUploadUrl:input_type -> team.v1.GetLogoUploadUrlRequest
	14, // 14: team.v1.TeamService.FinalizeLogoUpload:input_type -> team.v1.FinalizeLogoUploadRequest
	16, // 15: team.v1.TeamService.GetLogoUrl:input_type -> team.v1.GetLogoUrlRequest
	3,  // 16: team.v1.TeamService.CreateTeam:output_type -> team.v1.CreateTeamResponse
	5,  // 17: team.v1.TeamService.GetTeam:output_type -> team.v1.GetTeamResponse
	7,  // 18: team.v1.TeamService.ListTeams:output_type -> team.v1.ListTeamsResponse
	9,  // 19: team.v1.TeamService.UpdateTeam:output_type -> team.v1.UpdateTeamResponse
	11, // 20: team.v1.TeamService.DeleteTeam:output_type -> team.v1.DeleteTeamResponse
	13, // 21: team.v1.TeamService.GetLogoUploadUrl:output_type -> team.v1.GetLogoUploadUrlResponse
	15, // 22: team.v1.TeamService.FinalizeLogoUpload:output_type -> team.v1.FinalizeLogoUploadResponse
	17, // 23: team.v1.TeamService.GetLogoUrl:output_type -> team.v1.GetLogoUrlResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_team_v1_team_proto_init() }
func file_team_v1_team_proto_init() {
	if File_team_v1_team_proto != nil {
		return
	}
	file_team_v1_team_proto_msgTypes[4].OneofWrappers = []any{
		(*GetTeamRequest_Id)(nil),
		(*GetTeamRequest_Slug)(nil),
	}
	file_team_v1_team_proto_msgTypes[6].OneofWrappers = []any{}
	file_team_v1_team_proto_msgTypes[7].OneofWrappers = []any{}
	file_team_v1_team_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_v1_team_proto_rawDesc), len(file_team_v1_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_v1_team_proto_goTypes,
		DependencyIndexes: file_team_v1_team_proto_depIdxs,
		MessageInfos:      file_team_v1_team_proto_msgTypes,
	}.Build()
	File_team_v1_team_proto = out.File
	file_team_v1_team_proto_goTypes = nil
	file_team_v1_team_proto_depIdxs = nil
}
