// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: state_version/v1/state_version.proto

package stateVersionv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StorageKey    string                 `protobuf:"bytes,6,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateVersion) Reset() {
	*x = StateVersion{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateVersion) ProtoMessage() {}

func (x *StateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateVersion.ProtoReflect.Descriptor instead.
func (*StateVersion) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{0}
}

func (x *StateVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateVersion) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StateVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StateVersion) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *StateVersion) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *StateVersion) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *StateVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateStateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,2,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateVersionRequest) Reset() {
	*x = CreateStateVersionRequest{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateVersionRequest) ProtoMessage() {}

func (x *CreateStateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateStateVersionRequest) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStateVersionRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateStateVersionRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type CreateStateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateVersion  *StateVersion          `protobuf:"bytes,1,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateVersionResponse) Reset() {
	*x = CreateStateVersionResponse{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateVersionResponse) ProtoMessage() {}

func (x *CreateStateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateStateVersionResponse) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStateVersionResponse) GetStateVersion() *StateVersion {
	if x != nil {
		return x.StateVersion
	}
	return nil
}

type GetStateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateVersionRequest) Reset() {
	*x = GetStateVersionRequest{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateVersionRequest) ProtoMessage() {}

func (x *GetStateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateVersionRequest.ProtoReflect.Descriptor instead.
func (*GetStateVersionRequest) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateVersion  *StateVersion          `protobuf:"bytes,1,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateVersionResponse) Reset() {
	*x = GetStateVersionResponse{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateVersionResponse) ProtoMessage() {}

func (x *GetStateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateVersionResponse.ProtoReflect.Descriptor instead.
func (*GetStateVersionResponse) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateVersionResponse) GetStateVersion() *StateVersion {
	if x != nil {
		return x.StateVersion
	}
	return nil
}

type ListStateVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStateVersionsRequest) Reset() {
	*x = ListStateVersionsRequest{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStateVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStateVersionsRequest) ProtoMessage() {}

func (x *ListStateVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStateVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListStateVersionsRequest) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{5}
}

func (x *ListStateVersionsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListStateVersionsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListStateVersionsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListStateVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateVersions []*StateVersion        `protobuf:"bytes,1,rep,name=state_versions,json=stateVersions,proto3" json:"state_versions,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStateVersionsResponse) Reset() {
	*x = ListStateVersionsResponse{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStateVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStateVersionsResponse) ProtoMessage() {}

func (x *ListStateVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStateVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListStateVersionsResponse) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{6}
}

func (x *ListStateVersionsResponse) GetStateVersions() []*StateVersion {
	if x != nil {
		return x.StateVersions
	}
	return nil
}

func (x *ListStateVersionsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type DeleteStateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateVersionRequest) Reset() {
	*x = DeleteStateVersionRequest{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateVersionRequest) ProtoMessage() {}

func (x *DeleteStateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateVersionRequest) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStateVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateVersionResponse) Reset() {
	*x = DeleteStateVersionResponse{}
	mi := &file_state_version_v1_state_version_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateVersionResponse) ProtoMessage() {}

func (x *DeleteStateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_version_v1_state_version_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteStateVersionResponse) Descriptor() ([]byte, []int) {
	return file_state_version_v1_state_version_proto_rawDescGZIP(), []int{8}
}

var File_state_version_v1_state_version_proto protoreflect.FileDescriptor

const file_state_version_v1_state_version_proto_rawDesc = "" +
	"\n" +
	"$state_version/v1/state_version.proto\x12\x10state_version.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\fStateVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vstorage_key\x18\x06 \x01(\tR\n" +
	"storageKey\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"i\n" +
	"\x19CreateStateVersionRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12$\n" +
	"\vstorage_key\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"storageKey\"a\n" +
	"\x1aCreateStateVersionResponse\x12C\n" +
	"\rstate_version\x18\x01 \x01(\v2\x1e.state_version.v1.StateVersionR\fstateVersion\"-\n" +
	"\x16GetStateVersionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"^\n" +
	"\x17GetStateVersionResponse\x12C\n" +
	"\rstate_version\x18\x01 \x01(\v2\x1e.state_version.v1.StateVersionR\fstateVersion\"\xa5\x01\n" +
	"\x18ListStateVersionsRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xa3\x01\n" +
	"\x19ListStateVersionsResponse\x12E\n" +
	"\x0estate_versions\x18\x01 \x03(\v2\x1e.state_version.v1.StateVersionR\rstateVersions\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"0\n" +
	"\x19DeleteStateVersionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x1c\n" +
	"\x1aDeleteStateVersionResponse2\xcd\x03\n" +
	"\x13StateVersionService\x12o\n" +
	"\x12CreateStateVersion\x12+.state_version.v1.CreateStateVersionRequest\x1a,.state_version.v1.CreateStateVersionResponse\x12f\n" +
	"\x0fGetStateVersion\x12(.state_version.v1.GetStateVersionRequest\x1a).state_version.v1.GetStateVersionResponse\x12l\n" +
	"\x11ListStateVersions\x12*.state_version.v1.ListStateVersionsRequest\x1a+.state_version.v1.ListStateVersionsResponse\x12o\n" +
	"\x12DeleteStateVersion\x12+.state_version.v1.DeleteStateVersionRequest\x1a,.state_version.v1.DeleteStateVersionResponseBNZLgithub.com/terrabase-dev/terrabase-sdk/specs/state_version/v1;stateVersionv1b\x06proto3"

var (
	file_state_version_v1_state_version_proto_rawDescOnce sync.Once
	file_state_version_v1_state_version_proto_rawDescData []byte
)

func file_state_version_v1_state_version_proto_rawDescGZIP() []byte {
	file_state_version_v1_state_version_proto_rawDescOnce.Do(func() {
		file_state_version_v1_state_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_version_v1_state_version_proto_rawDesc), len(file_state_version_v1_state_version_proto_rawDesc)))
	})
	return file_state_version_v1_state_version_proto_rawDescData
}

var file_state_version_v1_state_version_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_state_version_v1_state_version_proto_goTypes = []any{
	(*StateVersion)(nil),               // 0: state_version.v1.StateVersion
	(*CreateStateVersionRequest)(nil),  // 1: state_version.v1.CreateStateVersionRequest
	(*CreateStateVersionResponse)(nil), // 2: state_version.v1.CreateStateVersionResponse
	(*GetStateVersionRequest)(nil),     // 3: state_version.v1.GetStateVersionRequest
	(*GetStateVersionResponse)(nil),    // 4: state_version.v1.GetStateVersionResponse
	(*ListStateVersionsRequest)(nil),   // 5: state_version.v1.ListStateVersionsRequest
	(*ListStateVersionsResponse)(nil),  // 6: state_version.v1.ListStateVersionsResponse
	(*DeleteStateVersionRequest)(nil),  // 7: state_version.v1.DeleteStateVersionRequest
	(*DeleteStateVersionResponse)(nil), // 8: state_version.v1.DeleteStateVersionResponse
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_state_version_v1_state_version_proto_depIdxs = []int32{
	9, // 0: state_version.v1.StateVersion.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: state_version.v1.CreateStateVersionResponse.state_version:type_name -> state_version.v1.StateVersion
	0, // 2: state_version.v1.GetStateVersionResponse.state_version:type_name -> state_version.v1.StateVersion
	0, // 3: state_version.v1.ListStateVersionsResponse.state_versions:type_name -> state_version.v1.StateVersion
	1, // 4: state_version.v1.StateVersionService.CreateStateVersion:input_type -> state_version.v1.CreateStateVersionRequest
	3, // 5: state_version.v1.StateVersionService.GetStateVersion:input_type -> state_version.v1.GetStateVersionRequest
	5, // 6: state_version.v1.StateVersionService.ListStateVersions:input_type -> state_version.v1.ListStateVersionsRequest
	7, // 7: state_version.v1.StateVersionService.DeleteStateVersion:input_type -> state_version.v1.DeleteStateVersionRequest
	2, // 8: state_version.v1.StateVersionService.CreateStateVersion:output_type -> state_version.v1.CreateStateVersionResponse
	4, // 9: state_version.v1.StateVersionService.GetStateVersion:output_type -> state_version.v1.GetStateVersionResponse
	6, // 10: state_version.v1.StateVersionService.ListStateVersions:output_type -> state_version.v1.ListStateVersionsResponse
	8, // 11: state_version.v1.StateVersionService.DeleteStateVersion:output_type -> state_version.v1.DeleteStateVersionResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_state_version_v1_state_version_proto_init() }
func file_state_version_v1_state_version_proto_init() {
	if File_state_version_v1_state_version_proto != nil {
		return
	}
	file_state_version_v1_state_version_proto_msgTypes[5].OneofWrappers = []any{}
	file_state_version_v1_state_version_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_version_v1_state_version_proto_rawDesc), len(file_state_version_v1_state_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_version_v1_state_version_proto_goTypes,
		DependencyIndexes: file_state_version_v1_state_version_proto_depIdxs,
		MessageInfos:      file_state_version_v1_state_version_proto_msgTypes,
	}.Build()
	File_state_version_v1_state_version_proto = out.File
	file_state_version_v1_state_version_proto_goTypes = nil
	file_state_version_v1_state_version_proto_depIdxs = nil
}
