// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: terraform/v1/terraform.proto

package terraformv1

import (
	_ "github.com/terrabase-dev/terrabase-sdk/specs/authz/v1"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/backend_config/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendConfig *v1.BackendConfig      `protobuf:"bytes,1,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetBackendConfig() *v1.BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{2}
}

func (x *PlanRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendConfig *v1.BackendConfig      `protobuf:"bytes,1,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{3}
}

func (x *PlanResponse) GetBackendConfig() *v1.BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendConfig *v1.BackendConfig      `protobuf:"bytes,1,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_terraform_v1_terraform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terraform_v1_terraform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_terraform_v1_terraform_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyResponse) GetBackendConfig() *v1.BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

var File_terraform_v1_terraform_proto protoreflect.FileDescriptor

const file_terraform_v1_terraform_proto_rawDesc = "" +
	"\n" +
	"\x1cterraform/v1/terraform.proto\x12\fterraform.v1\x1a\x14authz/v1/authz.proto\x1a&backend_config/v1/backend_config.proto\x1a\x1fgoogle/api/field_behavior.proto\"5\n" +
	"\vInitRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\"W\n" +
	"\fInitResponse\x12G\n" +
	"\x0ebackend_config\x18\x01 \x01(\v2 .backend_config.v1.BackendConfigR\rbackendConfig\"5\n" +
	"\vPlanRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\"W\n" +
	"\fPlanResponse\x12G\n" +
	"\x0ebackend_config\x18\x01 \x01(\v2 .backend_config.v1.BackendConfigR\rbackendConfig\"6\n" +
	"\fApplyRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\"X\n" +
	"\rApplyResponse\x12G\n" +
	"\x0ebackend_config\x18\x01 \x01(\v2 .backend_config.v1.BackendConfigR\rbackendConfig2\xf3\x01\n" +
	"\x10TerraformService\x12H\n" +
	"\x04Init\x12\x19.terraform.v1.InitRequest\x1a\x1a.terraform.v1.InitResponse\"\t\x88\xb5\x18\x01\x92\xb5\x18\x01\r\x12H\n" +
	"\x04Plan\x12\x19.terraform.v1.PlanRequest\x1a\x1a.terraform.v1.PlanResponse\"\t\x88\xb5\x18\x01\x92\xb5\x18\x01\x0e\x12K\n" +
	"\x05Apply\x12\x1a.terraform.v1.ApplyRequest\x1a\x1b.terraform.v1.ApplyResponse\"\t\x88\xb5\x18\x01\x92\xb5\x18\x01\x0fBGZEgithub.com/terrabase-dev/terrabase-sdk/specs/terraform/v1;terraformv1b\x06proto3"

var (
	file_terraform_v1_terraform_proto_rawDescOnce sync.Once
	file_terraform_v1_terraform_proto_rawDescData []byte
)

func file_terraform_v1_terraform_proto_rawDescGZIP() []byte {
	file_terraform_v1_terraform_proto_rawDescOnce.Do(func() {
		file_terraform_v1_terraform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terraform_v1_terraform_proto_rawDesc), len(file_terraform_v1_terraform_proto_rawDesc)))
	})
	return file_terraform_v1_terraform_proto_rawDescData
}

var file_terraform_v1_terraform_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_terraform_v1_terraform_proto_goTypes = []any{
	(*InitRequest)(nil),      // 0: terraform.v1.InitRequest
	(*InitResponse)(nil),     // 1: terraform.v1.InitResponse
	(*PlanRequest)(nil),      // 2: terraform.v1.PlanRequest
	(*PlanResponse)(nil),     // 3: terraform.v1.PlanResponse
	(*ApplyRequest)(nil),     // 4: terraform.v1.ApplyRequest
	(*ApplyResponse)(nil),    // 5: terraform.v1.ApplyResponse
	(*v1.BackendConfig)(nil), // 6: backend_config.v1.BackendConfig
}
var file_terraform_v1_terraform_proto_depIdxs = []int32{
	6, // 0: terraform.v1.InitResponse.backend_config:type_name -> backend_config.v1.BackendConfig
	6, // 1: terraform.v1.PlanResponse.backend_config:type_name -> backend_config.v1.BackendConfig
	6, // 2: terraform.v1.ApplyResponse.backend_config:type_name -> backend_config.v1.BackendConfig
	0, // 3: terraform.v1.TerraformService.Init:input_type -> terraform.v1.InitRequest
	2, // 4: terraform.v1.TerraformService.Plan:input_type -> terraform.v1.PlanRequest
	4, // 5: terraform.v1.TerraformService.Apply:input_type -> terraform.v1.ApplyRequest
	1, // 6: terraform.v1.TerraformService.Init:output_type -> terraform.v1.InitResponse
	3, // 7: terraform.v1.TerraformService.Plan:output_type -> terraform.v1.PlanResponse
	5, // 8: terraform.v1.TerraformService.Apply:output_type -> terraform.v1.ApplyResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_terraform_v1_terraform_proto_init() }
func file_terraform_v1_terraform_proto_init() {
	if File_terraform_v1_terraform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terraform_v1_terraform_proto_rawDesc), len(file_terraform_v1_terraform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terraform_v1_terraform_proto_goTypes,
		DependencyIndexes: file_terraform_v1_terraform_proto_depIdxs,
		MessageInfos:      file_terraform_v1_terraform_proto_msgTypes,
	}.Build()
	File_terraform_v1_terraform_proto = out.File
	file_terraform_v1_terraform_proto_goTypes = nil
	file_terraform_v1_terraform_proto_depIdxs = nil
}
