// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: application/v1/application.proto

package applicationv1

import (
	_ "github.com/terrabase-dev/terrabase-sdk/specs/authz/v1"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/environment/v1"
	v12 "github.com/terrabase-dev/terrabase-sdk/specs/team/v1"
	v11 "github.com/terrabase-dev/terrabase-sdk/specs/team_application_access_grant/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Terrabase application can be deployed in multiple environments, each with their own workspace
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the application
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The application's slug (used in URLs)
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// The description of the application
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The color of the application
	Color string `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	// The time the application was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who created the application
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the application was last updated at
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last updated the application
	UpdatedBy     string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_application_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Application) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Application) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Application) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Application) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Application) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Application) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type ApplicationSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application
	Application *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// The application environments
	Environments  []*v1.Environment `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationSummary) Reset() {
	*x = ApplicationSummary{}
	mi := &file_application_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationSummary) ProtoMessage() {}

func (x *ApplicationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationSummary.ProtoReflect.Descriptor instead.
func (*ApplicationSummary) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationSummary) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *ApplicationSummary) GetEnvironments() []*v1.Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

type CreateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ID of the team that owns the application
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The application's slug. A reasonable default will be generated if not provided.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// The description of the application
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The color of the application
	Color         *string `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateApplicationRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateApplicationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateApplicationRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type CreateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application that was created
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_application_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *CreateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*GetApplicationRequest_Id
	//	*GetApplicationRequest_Slug
	Key           isGetApplicationRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationRequest) GetKey() isGetApplicationRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		if x, ok := x.Key.(*GetApplicationRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetApplicationRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Key.(*GetApplicationRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetApplicationRequest_Key interface {
	isGetApplicationRequest_Key()
}

type GetApplicationRequest_Id struct {
	// The unique ID of the application
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetApplicationRequest_Slug struct {
	// The application's slug
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetApplicationRequest_Id) isGetApplicationRequest_Key() {}

func (*GetApplicationRequest_Slug) isGetApplicationRequest_Key() {}

type GetApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application information
	ApplicationSummary *ApplicationSummary `protobuf:"bytes,1,opt,name=application_summary,json=applicationSummary,proto3" json:"application_summary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_application_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *GetApplicationResponse) GetApplicationSummary() *ApplicationSummary {
	if x != nil {
		return x.ApplicationSummary
	}
	return nil
}

type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a team that owns applications
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The number of applications on each page of results
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// The token to retrieve the next page of results
	PageToken     *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_application_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *ListApplicationsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of application information
	ApplicationSummaries []*ApplicationSummary `protobuf:"bytes,1,rep,name=application_summaries,json=applicationSummaries,proto3" json:"application_summaries,omitempty"`
	// The token to retrieve the next page of results
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_application_v1_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{7}
}

func (x *ListApplicationsResponse) GetApplicationSummaries() []*ApplicationSummary {
	if x != nil {
		return x.ApplicationSummaries
	}
	return nil
}

func (x *ListApplicationsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application to update
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new name of the application
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The new slug for the application
	Slug *string `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	// The new description of the application
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The new color of the application
	Color         *string `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateApplicationRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateApplicationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateApplicationRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type UpdateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated application
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_application_v1_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type DeleteApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_application_v1_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_application_v1_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{11}
}

type GrantTeamAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of team access grants
	TeamAccessGrants []*v11.CreateTeamApplicationAccessGrantRequest `protobuf:"bytes,1,rep,name=team_access_grants,json=teamAccessGrants,proto3" json:"team_access_grants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrantTeamAccessRequest) Reset() {
	*x = GrantTeamAccessRequest{}
	mi := &file_application_v1_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessRequest) ProtoMessage() {}

func (x *GrantTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{12}
}

func (x *GrantTeamAccessRequest) GetTeamAccessGrants() []*v11.CreateTeamApplicationAccessGrantRequest {
	if x != nil {
		return x.TeamAccessGrants
	}
	return nil
}

type GrantTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTeamAccessResponse) Reset() {
	*x = GrantTeamAccessResponse{}
	mi := &file_application_v1_application_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessResponse) ProtoMessage() {}

func (x *GrantTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{13}
}

type RevokeTeamAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// A list of team IDs whose access to the application should be revoked
	TeamIds       *v12.TeamIds `protobuf:"bytes,2,opt,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessRequest) Reset() {
	*x = RevokeTeamAccessRequest{}
	mi := &file_application_v1_application_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessRequest) ProtoMessage() {}

func (x *RevokeTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeTeamAccessRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RevokeTeamAccessRequest) GetTeamIds() *v12.TeamIds {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type RevokeTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessResponse) Reset() {
	*x = RevokeTeamAccessResponse{}
	mi := &file_application_v1_application_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessResponse) ProtoMessage() {}

func (x *RevokeTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_v1_application_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_application_v1_application_proto_rawDescGZIP(), []int{15}
}

var File_application_v1_application_proto protoreflect.FileDescriptor

const file_application_v1_application_proto_rawDesc = "" +
	"\n" +
	" application/v1/application.proto\x12\x0eapplication.v1\x1a\x14authz/v1/authz.proto\x1a environment/v1/environment.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12team/v1/team.proto\x1aDteam_application_access_grant/v1/team_application_access_grant.proto\"\xb1\x02\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\"\x94\x01\n" +
	"\x12ApplicationSummary\x12=\n" +
	"\vapplication\x18\x01 \x01(\v2\x1b.application.v1.ApplicationR\vapplication\x12?\n" +
	"\fenvironments\x18\x02 \x03(\v2\x1b.environment.v1.EnvironmentR\fenvironments\"\xc1\x01\n" +
	"\x18CreateApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06teamId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x01R\x05color\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_color\"Z\n" +
	"\x19CreateApplicationResponse\x12=\n" +
	"\vapplication\x18\x01 \x01(\v2\x1b.application.v1.ApplicationR\vapplication\"F\n" +
	"\x15GetApplicationRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\x05\n" +
	"\x03key\"m\n" +
	"\x16GetApplicationResponse\x12S\n" +
	"\x13application_summary\x18\x01 \x01(\v2\".application.v1.ApplicationSummaryR\x12applicationSummary\"\x9a\x01\n" +
	"\x17ListApplicationsRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xb4\x01\n" +
	"\x18ListApplicationsResponse\x12W\n" +
	"\x15application_summaries\x18\x01 \x03(\v2\".application.v1.ApplicationSummaryR\x14applicationSummaries\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xcf\x01\n" +
	"\x18UpdateApplicationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x03R\x05color\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_color\"Z\n" +
	"\x19UpdateApplicationResponse\x12=\n" +
	"\vapplication\x18\x01 \x01(\v2\x1b.application.v1.ApplicationR\vapplication\"/\n" +
	"\x18DeleteApplicationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x1b\n" +
	"\x19DeleteApplicationResponse\"\x96\x01\n" +
	"\x16GrantTeamAccessRequest\x12|\n" +
	"\x12team_access_grants\x18\x01 \x03(\v2I.team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequestB\x03\xe0A\x02R\x10teamAccessGrants\"\x19\n" +
	"\x17GrantTeamAccessResponse\"w\n" +
	"\x17RevokeTeamAccessRequest\x12*\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\x03\xe0A\x02R\rapplicationId\x120\n" +
	"\bteam_ids\x18\x02 \x01(\v2\x10.team.v1.TeamIdsB\x03\xe0A\x02R\ateamIds\"\x1a\n" +
	"\x18RevokeTeamAccessResponse2\xcf\x06\n" +
	"\x12ApplicationService\x12x\n" +
	"\x11CreateApplication\x12(.application.v1.CreateApplicationRequest\x1a).application.v1.CreateApplicationResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\xa8\xb5\x18\x01\x12l\n" +
	"\x0eGetApplication\x12%.application.v1.GetApplicationRequest\x1a&.application.v1.GetApplicationResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\a\x06\x12r\n" +
	"\x10ListApplications\x12'.application.v1.ListApplicationsRequest\x1a(.application.v1.ListApplicationsResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\a\x06\x12x\n" +
	"\x11UpdateApplication\x12(.application.v1.UpdateApplicationRequest\x1a).application.v1.UpdateApplicationResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\xa8\xb5\x18\x01\x12x\n" +
	"\x11DeleteApplication\x12(.application.v1.DeleteApplicationRequest\x1a).application.v1.DeleteApplicationResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\xa8\xb5\x18\x01\x12r\n" +
	"\x0fGrantTeamAccess\x12&.application.v1.GrantTeamAccessRequest\x1a'.application.v1.GrantTeamAccessResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\xa8\xb5\x18\x01\x12u\n" +
	"\x10RevokeTeamAccess\x12'.application.v1.RevokeTeamAccessRequest\x1a(.application.v1.RevokeTeamAccessResponse\"\x0e\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\xa8\xb5\x18\x01BKZIgithub.com/terrabase-dev/terrabase-sdk/specs/application/v1;applicationv1b\x06proto3"

var (
	file_application_v1_application_proto_rawDescOnce sync.Once
	file_application_v1_application_proto_rawDescData []byte
)

func file_application_v1_application_proto_rawDescGZIP() []byte {
	file_application_v1_application_proto_rawDescOnce.Do(func() {
		file_application_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_v1_application_proto_rawDesc), len(file_application_v1_application_proto_rawDesc)))
	})
	return file_application_v1_application_proto_rawDescData
}

var file_application_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_application_v1_application_proto_goTypes = []any{
	(*Application)(nil),                                 // 0: application.v1.Application
	(*ApplicationSummary)(nil),                          // 1: application.v1.ApplicationSummary
	(*CreateApplicationRequest)(nil),                    // 2: application.v1.CreateApplicationRequest
	(*CreateApplicationResponse)(nil),                   // 3: application.v1.CreateApplicationResponse
	(*GetApplicationRequest)(nil),                       // 4: application.v1.GetApplicationRequest
	(*GetApplicationResponse)(nil),                      // 5: application.v1.GetApplicationResponse
	(*ListApplicationsRequest)(nil),                     // 6: application.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),                    // 7: application.v1.ListApplicationsResponse
	(*UpdateApplicationRequest)(nil),                    // 8: application.v1.UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil),                   // 9: application.v1.UpdateApplicationResponse
	(*DeleteApplicationRequest)(nil),                    // 10: application.v1.DeleteApplicationRequest
	(*DeleteApplicationResponse)(nil),                   // 11: application.v1.DeleteApplicationResponse
	(*GrantTeamAccessRequest)(nil),                      // 12: application.v1.GrantTeamAccessRequest
	(*GrantTeamAccessResponse)(nil),                     // 13: application.v1.GrantTeamAccessResponse
	(*RevokeTeamAccessRequest)(nil),                     // 14: application.v1.RevokeTeamAccessRequest
	(*RevokeTeamAccessResponse)(nil),                    // 15: application.v1.RevokeTeamAccessResponse
	(*timestamppb.Timestamp)(nil),                       // 16: google.protobuf.Timestamp
	(*v1.Environment)(nil),                              // 17: environment.v1.Environment
	(*v11.CreateTeamApplicationAccessGrantRequest)(nil), // 18: team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	(*v12.TeamIds)(nil),                                 // 19: team.v1.TeamIds
}
var file_application_v1_application_proto_depIdxs = []int32{
	16, // 0: application.v1.Application.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: application.v1.Application.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: application.v1.ApplicationSummary.application:type_name -> application.v1.Application
	17, // 3: application.v1.ApplicationSummary.environments:type_name -> environment.v1.Environment
	0,  // 4: application.v1.CreateApplicationResponse.application:type_name -> application.v1.Application
	1,  // 5: application.v1.GetApplicationResponse.application_summary:type_name -> application.v1.ApplicationSummary
	1,  // 6: application.v1.ListApplicationsResponse.application_summaries:type_name -> application.v1.ApplicationSummary
	0,  // 7: application.v1.UpdateApplicationResponse.application:type_name -> application.v1.Application
	18, // 8: application.v1.GrantTeamAccessRequest.team_access_grants:type_name -> team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	19, // 9: application.v1.RevokeTeamAccessRequest.team_ids:type_name -> team.v1.TeamIds
	2,  // 10: application.v1.ApplicationService.CreateApplication:input_type -> application.v1.CreateApplicationRequest
	4,  // 11: application.v1.ApplicationService.GetApplication:input_type -> application.v1.GetApplicationRequest
	6,  // 12: application.v1.ApplicationService.ListApplications:input_type -> application.v1.ListApplicationsRequest
	8,  // 13: application.v1.ApplicationService.UpdateApplication:input_type -> application.v1.UpdateApplicationRequest
	10, // 14: application.v1.ApplicationService.DeleteApplication:input_type -> application.v1.DeleteApplicationRequest
	12, // 15: application.v1.ApplicationService.GrantTeamAccess:input_type -> application.v1.GrantTeamAccessRequest
	14, // 16: application.v1.ApplicationService.RevokeTeamAccess:input_type -> application.v1.RevokeTeamAccessRequest
	3,  // 17: application.v1.ApplicationService.CreateApplication:output_type -> application.v1.CreateApplicationResponse
	5,  // 18: application.v1.ApplicationService.GetApplication:output_type -> application.v1.GetApplicationResponse
	7,  // 19: application.v1.ApplicationService.ListApplications:output_type -> application.v1.ListApplicationsResponse
	9,  // 20: application.v1.ApplicationService.UpdateApplication:output_type -> application.v1.UpdateApplicationResponse
	11, // 21: application.v1.ApplicationService.DeleteApplication:output_type -> application.v1.DeleteApplicationResponse
	13, // 22: application.v1.ApplicationService.GrantTeamAccess:output_type -> application.v1.GrantTeamAccessResponse
	15, // 23: application.v1.ApplicationService.RevokeTeamAccess:output_type -> application.v1.RevokeTeamAccessResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_application_v1_application_proto_init() }
func file_application_v1_application_proto_init() {
	if File_application_v1_application_proto != nil {
		return
	}
	file_application_v1_application_proto_msgTypes[2].OneofWrappers = []any{}
	file_application_v1_application_proto_msgTypes[4].OneofWrappers = []any{
		(*GetApplicationRequest_Id)(nil),
		(*GetApplicationRequest_Slug)(nil),
	}
	file_application_v1_application_proto_msgTypes[6].OneofWrappers = []any{}
	file_application_v1_application_proto_msgTypes[7].OneofWrappers = []any{}
	file_application_v1_application_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_v1_application_proto_rawDesc), len(file_application_v1_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_v1_application_proto_goTypes,
		DependencyIndexes: file_application_v1_application_proto_depIdxs,
		MessageInfos:      file_application_v1_application_proto_msgTypes,
	}.Build()
	File_application_v1_application_proto = out.File
	file_application_v1_application_proto_goTypes = nil
	file_application_v1_application_proto_depIdxs = nil
}
