// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file state_version/v1/state_version.proto (package state_version.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file state_version/v1/state_version.proto.
 */
export const file_state_version_v1_state_version: GenFile = /*@__PURE__*/
  fileDesc("CiRzdGF0ZV92ZXJzaW9uL3YxL3N0YXRlX3ZlcnNpb24ucHJvdG8SEHN0YXRlX3ZlcnNpb24udjEiqAEKDFN0YXRlVmVyc2lvbhIKCgJpZBgBIAEoCRIUCgx3b3Jrc3BhY2VfaWQYAiABKAkSDwoHdmVyc2lvbhgDIAEoCRIMCgRoYXNoGAQgASgJEhIKCnNpemVfYnl0ZXMYBSABKAMSEwoLc3RvcmFnZV9rZXkYBiABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiUAoZQ3JlYXRlU3RhdGVWZXJzaW9uUmVxdWVzdBIZCgx3b3Jrc3BhY2VfaWQYASABKAlCA+BBAhIYCgtzdG9yYWdlX2tleRgCIAEoCUID4EECIlMKGkNyZWF0ZVN0YXRlVmVyc2lvblJlc3BvbnNlEjUKDXN0YXRlX3ZlcnNpb24YASABKAsyHi5zdGF0ZV92ZXJzaW9uLnYxLlN0YXRlVmVyc2lvbiIpChZHZXRTdGF0ZVZlcnNpb25SZXF1ZXN0Eg8KAmlkGAEgASgJQgPgQQIiUAoXR2V0U3RhdGVWZXJzaW9uUmVzcG9uc2USNQoNc3RhdGVfdmVyc2lvbhgBIAEoCzIeLnN0YXRlX3ZlcnNpb24udjEuU3RhdGVWZXJzaW9uIoMBChhMaXN0U3RhdGVWZXJzaW9uc1JlcXVlc3QSGQoMd29ya3NwYWNlX2lkGAEgASgJQgPgQQISFgoJcGFnZV9zaXplGAIgASgFSACIAQESFwoKcGFnZV90b2tlbhgDIAEoCUgBiAEBQgwKCl9wYWdlX3NpemVCDQoLX3BhZ2VfdG9rZW4ihQEKGUxpc3RTdGF0ZVZlcnNpb25zUmVzcG9uc2USNgoOc3RhdGVfdmVyc2lvbnMYASADKAsyHi5zdGF0ZV92ZXJzaW9uLnYxLlN0YXRlVmVyc2lvbhIcCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAlIAIgBAUISChBfbmV4dF9wYWdlX3Rva2VuIiwKGURlbGV0ZVN0YXRlVmVyc2lvblJlcXVlc3QSDwoCaWQYASABKAlCA+BBAiIcChpEZWxldGVTdGF0ZVZlcnNpb25SZXNwb25zZTLNAwoTU3RhdGVWZXJzaW9uU2VydmljZRJvChJDcmVhdGVTdGF0ZVZlcnNpb24SKy5zdGF0ZV92ZXJzaW9uLnYxLkNyZWF0ZVN0YXRlVmVyc2lvblJlcXVlc3QaLC5zdGF0ZV92ZXJzaW9uLnYxLkNyZWF0ZVN0YXRlVmVyc2lvblJlc3BvbnNlEmYKD0dldFN0YXRlVmVyc2lvbhIoLnN0YXRlX3ZlcnNpb24udjEuR2V0U3RhdGVWZXJzaW9uUmVxdWVzdBopLnN0YXRlX3ZlcnNpb24udjEuR2V0U3RhdGVWZXJzaW9uUmVzcG9uc2USbAoRTGlzdFN0YXRlVmVyc2lvbnMSKi5zdGF0ZV92ZXJzaW9uLnYxLkxpc3RTdGF0ZVZlcnNpb25zUmVxdWVzdBorLnN0YXRlX3ZlcnNpb24udjEuTGlzdFN0YXRlVmVyc2lvbnNSZXNwb25zZRJvChJEZWxldGVTdGF0ZVZlcnNpb24SKy5zdGF0ZV92ZXJzaW9uLnYxLkRlbGV0ZVN0YXRlVmVyc2lvblJlcXVlc3QaLC5zdGF0ZV92ZXJzaW9uLnYxLkRlbGV0ZVN0YXRlVmVyc2lvblJlc3BvbnNlQk5aTGdpdGh1Yi5jb20vdGVycmFiYXNlLWRldi90ZXJyYWJhc2Utc2RrL3NwZWNzL3N0YXRlX3ZlcnNpb24vdjE7c3RhdGVWZXJzaW9udjFiBnByb3RvMw", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * @generated from message state_version.v1.StateVersion
 */
export type StateVersion = Message<"state_version.v1.StateVersion"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: string hash = 4;
   */
  hash: string;

  /**
   * @generated from field: int64 size_bytes = 5;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string storage_key = 6;
   */
  storageKey: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message state_version.v1.StateVersion.
 * Use `create(StateVersionSchema)` to create a new message.
 */
export const StateVersionSchema: GenMessage<StateVersion> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 0);

/**
 * @generated from message state_version.v1.CreateStateVersionRequest
 */
export type CreateStateVersionRequest = Message<"state_version.v1.CreateStateVersionRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string storage_key = 2;
   */
  storageKey: string;
};

/**
 * Describes the message state_version.v1.CreateStateVersionRequest.
 * Use `create(CreateStateVersionRequestSchema)` to create a new message.
 */
export const CreateStateVersionRequestSchema: GenMessage<CreateStateVersionRequest> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 1);

/**
 * @generated from message state_version.v1.CreateStateVersionResponse
 */
export type CreateStateVersionResponse = Message<"state_version.v1.CreateStateVersionResponse"> & {
  /**
   * @generated from field: state_version.v1.StateVersion state_version = 1;
   */
  stateVersion?: StateVersion;
};

/**
 * Describes the message state_version.v1.CreateStateVersionResponse.
 * Use `create(CreateStateVersionResponseSchema)` to create a new message.
 */
export const CreateStateVersionResponseSchema: GenMessage<CreateStateVersionResponse> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 2);

/**
 * @generated from message state_version.v1.GetStateVersionRequest
 */
export type GetStateVersionRequest = Message<"state_version.v1.GetStateVersionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message state_version.v1.GetStateVersionRequest.
 * Use `create(GetStateVersionRequestSchema)` to create a new message.
 */
export const GetStateVersionRequestSchema: GenMessage<GetStateVersionRequest> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 3);

/**
 * @generated from message state_version.v1.GetStateVersionResponse
 */
export type GetStateVersionResponse = Message<"state_version.v1.GetStateVersionResponse"> & {
  /**
   * @generated from field: state_version.v1.StateVersion state_version = 1;
   */
  stateVersion?: StateVersion;
};

/**
 * Describes the message state_version.v1.GetStateVersionResponse.
 * Use `create(GetStateVersionResponseSchema)` to create a new message.
 */
export const GetStateVersionResponseSchema: GenMessage<GetStateVersionResponse> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 4);

/**
 * @generated from message state_version.v1.ListStateVersionsRequest
 */
export type ListStateVersionsRequest = Message<"state_version.v1.ListStateVersionsRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: optional int32 page_size = 2;
   */
  pageSize?: number;

  /**
   * @generated from field: optional string page_token = 3;
   */
  pageToken?: string;
};

/**
 * Describes the message state_version.v1.ListStateVersionsRequest.
 * Use `create(ListStateVersionsRequestSchema)` to create a new message.
 */
export const ListStateVersionsRequestSchema: GenMessage<ListStateVersionsRequest> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 5);

/**
 * @generated from message state_version.v1.ListStateVersionsResponse
 */
export type ListStateVersionsResponse = Message<"state_version.v1.ListStateVersionsResponse"> & {
  /**
   * @generated from field: repeated state_version.v1.StateVersion state_versions = 1;
   */
  stateVersions: StateVersion[];

  /**
   * @generated from field: optional string next_page_token = 2;
   */
  nextPageToken?: string;
};

/**
 * Describes the message state_version.v1.ListStateVersionsResponse.
 * Use `create(ListStateVersionsResponseSchema)` to create a new message.
 */
export const ListStateVersionsResponseSchema: GenMessage<ListStateVersionsResponse> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 6);

/**
 * @generated from message state_version.v1.DeleteStateVersionRequest
 */
export type DeleteStateVersionRequest = Message<"state_version.v1.DeleteStateVersionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message state_version.v1.DeleteStateVersionRequest.
 * Use `create(DeleteStateVersionRequestSchema)` to create a new message.
 */
export const DeleteStateVersionRequestSchema: GenMessage<DeleteStateVersionRequest> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 7);

/**
 * @generated from message state_version.v1.DeleteStateVersionResponse
 */
export type DeleteStateVersionResponse = Message<"state_version.v1.DeleteStateVersionResponse"> & {
};

/**
 * Describes the message state_version.v1.DeleteStateVersionResponse.
 * Use `create(DeleteStateVersionResponseSchema)` to create a new message.
 */
export const DeleteStateVersionResponseSchema: GenMessage<DeleteStateVersionResponse> = /*@__PURE__*/
  messageDesc(file_state_version_v1_state_version, 8);

/**
 * @generated from service state_version.v1.StateVersionService
 */
export const StateVersionService: GenService<{
  /**
   * @generated from rpc state_version.v1.StateVersionService.CreateStateVersion
   */
  createStateVersion: {
    methodKind: "unary";
    input: typeof CreateStateVersionRequestSchema;
    output: typeof CreateStateVersionResponseSchema;
  },
  /**
   * @generated from rpc state_version.v1.StateVersionService.GetStateVersion
   */
  getStateVersion: {
    methodKind: "unary";
    input: typeof GetStateVersionRequestSchema;
    output: typeof GetStateVersionResponseSchema;
  },
  /**
   * @generated from rpc state_version.v1.StateVersionService.ListStateVersions
   */
  listStateVersions: {
    methodKind: "unary";
    input: typeof ListStateVersionsRequestSchema;
    output: typeof ListStateVersionsResponseSchema;
  },
  /**
   * @generated from rpc state_version.v1.StateVersionService.DeleteStateVersion
   */
  deleteStateVersion: {
    methodKind: "unary";
    input: typeof DeleteStateVersionRequestSchema;
    output: typeof DeleteStateVersionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_state_version_v1_state_version, 0);

