// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: application/v1/application.proto

package applicationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/application/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApplicationServiceName is the fully-qualified name of the ApplicationService service.
	ApplicationServiceName = "application.v1.ApplicationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApplicationServiceCreateApplicationProcedure is the fully-qualified name of the
	// ApplicationService's CreateApplication RPC.
	ApplicationServiceCreateApplicationProcedure = "/application.v1.ApplicationService/CreateApplication"
	// ApplicationServiceGetApplicationProcedure is the fully-qualified name of the ApplicationService's
	// GetApplication RPC.
	ApplicationServiceGetApplicationProcedure = "/application.v1.ApplicationService/GetApplication"
	// ApplicationServiceListApplicationsProcedure is the fully-qualified name of the
	// ApplicationService's ListApplications RPC.
	ApplicationServiceListApplicationsProcedure = "/application.v1.ApplicationService/ListApplications"
	// ApplicationServiceUpdateApplicationProcedure is the fully-qualified name of the
	// ApplicationService's UpdateApplication RPC.
	ApplicationServiceUpdateApplicationProcedure = "/application.v1.ApplicationService/UpdateApplication"
	// ApplicationServiceDeleteApplicationProcedure is the fully-qualified name of the
	// ApplicationService's DeleteApplication RPC.
	ApplicationServiceDeleteApplicationProcedure = "/application.v1.ApplicationService/DeleteApplication"
	// ApplicationServiceGrantTeamAccessProcedure is the fully-qualified name of the
	// ApplicationService's GrantTeamAccess RPC.
	ApplicationServiceGrantTeamAccessProcedure = "/application.v1.ApplicationService/GrantTeamAccess"
	// ApplicationServiceRevokeTeamAccessProcedure is the fully-qualified name of the
	// ApplicationService's RevokeTeamAccess RPC.
	ApplicationServiceRevokeTeamAccessProcedure = "/application.v1.ApplicationService/RevokeTeamAccess"
)

// ApplicationServiceClient is a client for the application.v1.ApplicationService service.
type ApplicationServiceClient interface {
	// Create a new application
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error)
	// Retrieve details about a single application
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	// List applications owned by a specific team
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	// Change details about an application
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error)
	// Delete an application
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error)
	// Grant access to an application to a single team or multiple teams
	GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error)
	// Revoke access to an application from a single team or multiple teams
	RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error)
}

// NewApplicationServiceClient constructs a client for the application.v1.ApplicationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApplicationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApplicationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	applicationServiceMethods := v1.File_application_v1_application_proto.Services().ByName("ApplicationService").Methods()
	return &applicationServiceClient{
		createApplication: connect.NewClient[v1.CreateApplicationRequest, v1.CreateApplicationResponse](
			httpClient,
			baseURL+ApplicationServiceCreateApplicationProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("CreateApplication")),
			connect.WithClientOptions(opts...),
		),
		getApplication: connect.NewClient[v1.GetApplicationRequest, v1.GetApplicationResponse](
			httpClient,
			baseURL+ApplicationServiceGetApplicationProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("GetApplication")),
			connect.WithClientOptions(opts...),
		),
		listApplications: connect.NewClient[v1.ListApplicationsRequest, v1.ListApplicationsResponse](
			httpClient,
			baseURL+ApplicationServiceListApplicationsProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("ListApplications")),
			connect.WithClientOptions(opts...),
		),
		updateApplication: connect.NewClient[v1.UpdateApplicationRequest, v1.UpdateApplicationResponse](
			httpClient,
			baseURL+ApplicationServiceUpdateApplicationProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("UpdateApplication")),
			connect.WithClientOptions(opts...),
		),
		deleteApplication: connect.NewClient[v1.DeleteApplicationRequest, v1.DeleteApplicationResponse](
			httpClient,
			baseURL+ApplicationServiceDeleteApplicationProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("DeleteApplication")),
			connect.WithClientOptions(opts...),
		),
		grantTeamAccess: connect.NewClient[v1.GrantTeamAccessRequest, v1.GrantTeamAccessResponse](
			httpClient,
			baseURL+ApplicationServiceGrantTeamAccessProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("GrantTeamAccess")),
			connect.WithClientOptions(opts...),
		),
		revokeTeamAccess: connect.NewClient[v1.RevokeTeamAccessRequest, v1.RevokeTeamAccessResponse](
			httpClient,
			baseURL+ApplicationServiceRevokeTeamAccessProcedure,
			connect.WithSchema(applicationServiceMethods.ByName("RevokeTeamAccess")),
			connect.WithClientOptions(opts...),
		),
	}
}

// applicationServiceClient implements ApplicationServiceClient.
type applicationServiceClient struct {
	createApplication *connect.Client[v1.CreateApplicationRequest, v1.CreateApplicationResponse]
	getApplication    *connect.Client[v1.GetApplicationRequest, v1.GetApplicationResponse]
	listApplications  *connect.Client[v1.ListApplicationsRequest, v1.ListApplicationsResponse]
	updateApplication *connect.Client[v1.UpdateApplicationRequest, v1.UpdateApplicationResponse]
	deleteApplication *connect.Client[v1.DeleteApplicationRequest, v1.DeleteApplicationResponse]
	grantTeamAccess   *connect.Client[v1.GrantTeamAccessRequest, v1.GrantTeamAccessResponse]
	revokeTeamAccess  *connect.Client[v1.RevokeTeamAccessRequest, v1.RevokeTeamAccessResponse]
}

// CreateApplication calls application.v1.ApplicationService.CreateApplication.
func (c *applicationServiceClient) CreateApplication(ctx context.Context, req *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error) {
	return c.createApplication.CallUnary(ctx, req)
}

// GetApplication calls application.v1.ApplicationService.GetApplication.
func (c *applicationServiceClient) GetApplication(ctx context.Context, req *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return c.getApplication.CallUnary(ctx, req)
}

// ListApplications calls application.v1.ApplicationService.ListApplications.
func (c *applicationServiceClient) ListApplications(ctx context.Context, req *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return c.listApplications.CallUnary(ctx, req)
}

// UpdateApplication calls application.v1.ApplicationService.UpdateApplication.
func (c *applicationServiceClient) UpdateApplication(ctx context.Context, req *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error) {
	return c.updateApplication.CallUnary(ctx, req)
}

// DeleteApplication calls application.v1.ApplicationService.DeleteApplication.
func (c *applicationServiceClient) DeleteApplication(ctx context.Context, req *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error) {
	return c.deleteApplication.CallUnary(ctx, req)
}

// GrantTeamAccess calls application.v1.ApplicationService.GrantTeamAccess.
func (c *applicationServiceClient) GrantTeamAccess(ctx context.Context, req *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error) {
	return c.grantTeamAccess.CallUnary(ctx, req)
}

// RevokeTeamAccess calls application.v1.ApplicationService.RevokeTeamAccess.
func (c *applicationServiceClient) RevokeTeamAccess(ctx context.Context, req *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error) {
	return c.revokeTeamAccess.CallUnary(ctx, req)
}

// ApplicationServiceHandler is an implementation of the application.v1.ApplicationService service.
type ApplicationServiceHandler interface {
	// Create a new application
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error)
	// Retrieve details about a single application
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	// List applications owned by a specific team
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	// Change details about an application
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error)
	// Delete an application
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error)
	// Grant access to an application to a single team or multiple teams
	GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error)
	// Revoke access to an application from a single team or multiple teams
	RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error)
}

// NewApplicationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApplicationServiceHandler(svc ApplicationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	applicationServiceMethods := v1.File_application_v1_application_proto.Services().ByName("ApplicationService").Methods()
	applicationServiceCreateApplicationHandler := connect.NewUnaryHandler(
		ApplicationServiceCreateApplicationProcedure,
		svc.CreateApplication,
		connect.WithSchema(applicationServiceMethods.ByName("CreateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceGetApplicationHandler := connect.NewUnaryHandler(
		ApplicationServiceGetApplicationProcedure,
		svc.GetApplication,
		connect.WithSchema(applicationServiceMethods.ByName("GetApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceListApplicationsHandler := connect.NewUnaryHandler(
		ApplicationServiceListApplicationsProcedure,
		svc.ListApplications,
		connect.WithSchema(applicationServiceMethods.ByName("ListApplications")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceUpdateApplicationHandler := connect.NewUnaryHandler(
		ApplicationServiceUpdateApplicationProcedure,
		svc.UpdateApplication,
		connect.WithSchema(applicationServiceMethods.ByName("UpdateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceDeleteApplicationHandler := connect.NewUnaryHandler(
		ApplicationServiceDeleteApplicationProcedure,
		svc.DeleteApplication,
		connect.WithSchema(applicationServiceMethods.ByName("DeleteApplication")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceGrantTeamAccessHandler := connect.NewUnaryHandler(
		ApplicationServiceGrantTeamAccessProcedure,
		svc.GrantTeamAccess,
		connect.WithSchema(applicationServiceMethods.ByName("GrantTeamAccess")),
		connect.WithHandlerOptions(opts...),
	)
	applicationServiceRevokeTeamAccessHandler := connect.NewUnaryHandler(
		ApplicationServiceRevokeTeamAccessProcedure,
		svc.RevokeTeamAccess,
		connect.WithSchema(applicationServiceMethods.ByName("RevokeTeamAccess")),
		connect.WithHandlerOptions(opts...),
	)
	return "/application.v1.ApplicationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApplicationServiceCreateApplicationProcedure:
			applicationServiceCreateApplicationHandler.ServeHTTP(w, r)
		case ApplicationServiceGetApplicationProcedure:
			applicationServiceGetApplicationHandler.ServeHTTP(w, r)
		case ApplicationServiceListApplicationsProcedure:
			applicationServiceListApplicationsHandler.ServeHTTP(w, r)
		case ApplicationServiceUpdateApplicationProcedure:
			applicationServiceUpdateApplicationHandler.ServeHTTP(w, r)
		case ApplicationServiceDeleteApplicationProcedure:
			applicationServiceDeleteApplicationHandler.ServeHTTP(w, r)
		case ApplicationServiceGrantTeamAccessProcedure:
			applicationServiceGrantTeamAccessHandler.ServeHTTP(w, r)
		case ApplicationServiceRevokeTeamAccessProcedure:
			applicationServiceRevokeTeamAccessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApplicationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApplicationServiceHandler struct{}

func (UnimplementedApplicationServiceHandler) CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.CreateApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.CreateApplication is not implemented"))
}

func (UnimplementedApplicationServiceHandler) GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.GetApplication is not implemented"))
}

func (UnimplementedApplicationServiceHandler) ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.ListApplications is not implemented"))
}

func (UnimplementedApplicationServiceHandler) UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.UpdateApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.UpdateApplication is not implemented"))
}

func (UnimplementedApplicationServiceHandler) DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[v1.DeleteApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.DeleteApplication is not implemented"))
}

func (UnimplementedApplicationServiceHandler) GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.GrantTeamAccess is not implemented"))
}

func (UnimplementedApplicationServiceHandler) RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("application.v1.ApplicationService.RevokeTeamAccess is not implemented"))
}
