// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workspace/v1/workspace.proto

package workspacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/workspace/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkspaceServiceName is the fully-qualified name of the WorkspaceService service.
	WorkspaceServiceName = "workspace.v1.WorkspaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkspaceServiceCreateWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// CreateWorkspace RPC.
	WorkspaceServiceCreateWorkspaceProcedure = "/workspace.v1.WorkspaceService/CreateWorkspace"
	// WorkspaceServiceGetWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// GetWorkspace RPC.
	WorkspaceServiceGetWorkspaceProcedure = "/workspace.v1.WorkspaceService/GetWorkspace"
	// WorkspaceServiceListWorkspacesProcedure is the fully-qualified name of the WorkspaceService's
	// ListWorkspaces RPC.
	WorkspaceServiceListWorkspacesProcedure = "/workspace.v1.WorkspaceService/ListWorkspaces"
	// WorkspaceServiceUpdateWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// UpdateWorkspace RPC.
	WorkspaceServiceUpdateWorkspaceProcedure = "/workspace.v1.WorkspaceService/UpdateWorkspace"
	// WorkspaceServiceDeleteWorkspaceProcedure is the fully-qualified name of the WorkspaceService's
	// DeleteWorkspace RPC.
	WorkspaceServiceDeleteWorkspaceProcedure = "/workspace.v1.WorkspaceService/DeleteWorkspace"
	// WorkspaceServiceGrantTeamAccessProcedure is the fully-qualified name of the WorkspaceService's
	// GrantTeamAccess RPC.
	WorkspaceServiceGrantTeamAccessProcedure = "/workspace.v1.WorkspaceService/GrantTeamAccess"
	// WorkspaceServiceRevokeTeamAccessProcedure is the fully-qualified name of the WorkspaceService's
	// RevokeTeamAccess RPC.
	WorkspaceServiceRevokeTeamAccessProcedure = "/workspace.v1.WorkspaceService/RevokeTeamAccess"
)

// WorkspaceServiceClient is a client for the workspace.v1.WorkspaceService service.
type WorkspaceServiceClient interface {
	// Create a new workspace
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	// Retrieve details about a single workspace
	GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error)
	// List workspaces owned by a specific team, or belong to a specific application
	ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error)
	// Change details about a workspace
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	// Delete a workspace
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	// Grant access to a workspace to a single team or multiple teams
	GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error)
	// Revoke access to a workspace from a single team or multiple teams
	RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error)
}

// NewWorkspaceServiceClient constructs a client for the workspace.v1.WorkspaceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkspaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkspaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workspaceServiceMethods := v1.File_workspace_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	return &workspaceServiceClient{
		createWorkspace: connect.NewClient[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceCreateWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		getWorkspace: connect.NewClient[v1.GetWorkspaceRequest, v1.GetWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceGetWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GetWorkspace")),
			connect.WithClientOptions(opts...),
		),
		listWorkspaces: connect.NewClient[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse](
			httpClient,
			baseURL+WorkspaceServiceListWorkspacesProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("ListWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		updateWorkspace: connect.NewClient[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceUpdateWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		deleteWorkspace: connect.NewClient[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse](
			httpClient,
			baseURL+WorkspaceServiceDeleteWorkspaceProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkspace")),
			connect.WithClientOptions(opts...),
		),
		grantTeamAccess: connect.NewClient[v1.GrantTeamAccessRequest, v1.GrantTeamAccessResponse](
			httpClient,
			baseURL+WorkspaceServiceGrantTeamAccessProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("GrantTeamAccess")),
			connect.WithClientOptions(opts...),
		),
		revokeTeamAccess: connect.NewClient[v1.RevokeTeamAccessRequest, v1.RevokeTeamAccessResponse](
			httpClient,
			baseURL+WorkspaceServiceRevokeTeamAccessProcedure,
			connect.WithSchema(workspaceServiceMethods.ByName("RevokeTeamAccess")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workspaceServiceClient implements WorkspaceServiceClient.
type workspaceServiceClient struct {
	createWorkspace  *connect.Client[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse]
	getWorkspace     *connect.Client[v1.GetWorkspaceRequest, v1.GetWorkspaceResponse]
	listWorkspaces   *connect.Client[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse]
	updateWorkspace  *connect.Client[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse]
	deleteWorkspace  *connect.Client[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse]
	grantTeamAccess  *connect.Client[v1.GrantTeamAccessRequest, v1.GrantTeamAccessResponse]
	revokeTeamAccess *connect.Client[v1.RevokeTeamAccessRequest, v1.RevokeTeamAccessResponse]
}

// CreateWorkspace calls workspace.v1.WorkspaceService.CreateWorkspace.
func (c *workspaceServiceClient) CreateWorkspace(ctx context.Context, req *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return c.createWorkspace.CallUnary(ctx, req)
}

// GetWorkspace calls workspace.v1.WorkspaceService.GetWorkspace.
func (c *workspaceServiceClient) GetWorkspace(ctx context.Context, req *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error) {
	return c.getWorkspace.CallUnary(ctx, req)
}

// ListWorkspaces calls workspace.v1.WorkspaceService.ListWorkspaces.
func (c *workspaceServiceClient) ListWorkspaces(ctx context.Context, req *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error) {
	return c.listWorkspaces.CallUnary(ctx, req)
}

// UpdateWorkspace calls workspace.v1.WorkspaceService.UpdateWorkspace.
func (c *workspaceServiceClient) UpdateWorkspace(ctx context.Context, req *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return c.updateWorkspace.CallUnary(ctx, req)
}

// DeleteWorkspace calls workspace.v1.WorkspaceService.DeleteWorkspace.
func (c *workspaceServiceClient) DeleteWorkspace(ctx context.Context, req *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return c.deleteWorkspace.CallUnary(ctx, req)
}

// GrantTeamAccess calls workspace.v1.WorkspaceService.GrantTeamAccess.
func (c *workspaceServiceClient) GrantTeamAccess(ctx context.Context, req *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error) {
	return c.grantTeamAccess.CallUnary(ctx, req)
}

// RevokeTeamAccess calls workspace.v1.WorkspaceService.RevokeTeamAccess.
func (c *workspaceServiceClient) RevokeTeamAccess(ctx context.Context, req *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error) {
	return c.revokeTeamAccess.CallUnary(ctx, req)
}

// WorkspaceServiceHandler is an implementation of the workspace.v1.WorkspaceService service.
type WorkspaceServiceHandler interface {
	// Create a new workspace
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	// Retrieve details about a single workspace
	GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error)
	// List workspaces owned by a specific team, or belong to a specific application
	ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error)
	// Change details about a workspace
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	// Delete a workspace
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	// Grant access to a workspace to a single team or multiple teams
	GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error)
	// Revoke access to a workspace from a single team or multiple teams
	RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error)
}

// NewWorkspaceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkspaceServiceHandler(svc WorkspaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workspaceServiceMethods := v1.File_workspace_v1_workspace_proto.Services().ByName("WorkspaceService").Methods()
	workspaceServiceCreateWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceCreateWorkspaceProcedure,
		svc.CreateWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("CreateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGetWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceGetWorkspaceProcedure,
		svc.GetWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("GetWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceListWorkspacesHandler := connect.NewUnaryHandler(
		WorkspaceServiceListWorkspacesProcedure,
		svc.ListWorkspaces,
		connect.WithSchema(workspaceServiceMethods.ByName("ListWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceUpdateWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceUpdateWorkspaceProcedure,
		svc.UpdateWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("UpdateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceDeleteWorkspaceHandler := connect.NewUnaryHandler(
		WorkspaceServiceDeleteWorkspaceProcedure,
		svc.DeleteWorkspace,
		connect.WithSchema(workspaceServiceMethods.ByName("DeleteWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceGrantTeamAccessHandler := connect.NewUnaryHandler(
		WorkspaceServiceGrantTeamAccessProcedure,
		svc.GrantTeamAccess,
		connect.WithSchema(workspaceServiceMethods.ByName("GrantTeamAccess")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceServiceRevokeTeamAccessHandler := connect.NewUnaryHandler(
		WorkspaceServiceRevokeTeamAccessProcedure,
		svc.RevokeTeamAccess,
		connect.WithSchema(workspaceServiceMethods.ByName("RevokeTeamAccess")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workspace.v1.WorkspaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkspaceServiceCreateWorkspaceProcedure:
			workspaceServiceCreateWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceGetWorkspaceProcedure:
			workspaceServiceGetWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceListWorkspacesProcedure:
			workspaceServiceListWorkspacesHandler.ServeHTTP(w, r)
		case WorkspaceServiceUpdateWorkspaceProcedure:
			workspaceServiceUpdateWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceDeleteWorkspaceProcedure:
			workspaceServiceDeleteWorkspaceHandler.ServeHTTP(w, r)
		case WorkspaceServiceGrantTeamAccessProcedure:
			workspaceServiceGrantTeamAccessHandler.ServeHTTP(w, r)
		case WorkspaceServiceRevokeTeamAccessProcedure:
			workspaceServiceRevokeTeamAccessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkspaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkspaceServiceHandler struct{}

func (UnimplementedWorkspaceServiceHandler) CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.CreateWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GetWorkspace(context.Context, *connect.Request[v1.GetWorkspaceRequest]) (*connect.Response[v1.GetWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.GetWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) ListWorkspaces(context.Context, *connect.Request[v1.ListWorkspacesRequest]) (*connect.Response[v1.ListWorkspacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.ListWorkspaces is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.UpdateWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.DeleteWorkspace is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) GrantTeamAccess(context.Context, *connect.Request[v1.GrantTeamAccessRequest]) (*connect.Response[v1.GrantTeamAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.GrantTeamAccess is not implemented"))
}

func (UnimplementedWorkspaceServiceHandler) RevokeTeamAccess(context.Context, *connect.Request[v1.RevokeTeamAccessRequest]) (*connect.Response[v1.RevokeTeamAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.v1.WorkspaceService.RevokeTeamAccess is not implemented"))
}
