// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: team_application_access_grant/v1/team_application_access_grant.proto

package teamApplicationAccessGrantv1

import (
	_ "github.com/terrabase-dev/terrabase-sdk/specs/authz/v1"
	v1 "github.com/terrabase-dev/terrabase-sdk/specs/team_access_type/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Grants a team access to an application
type TeamApplicationAccessGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the team that has access to the application
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the application the team has access to
	ApplicationId string `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// The type of access the team has to the application
	AccessType v1.TeamAccessType `protobuf:"varint,4,opt,name=access_type,json=accessType,proto3,enum=team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	// The time the access to the application was granted to the team
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The user who granted access to the application to the team
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// The time the team's access to the application was last changed
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The user who last changed the team's access to the application
	UpdatedBy     string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamApplicationAccessGrant) Reset() {
	*x = TeamApplicationAccessGrant{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamApplicationAccessGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamApplicationAccessGrant) ProtoMessage() {}

func (x *TeamApplicationAccessGrant) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamApplicationAccessGrant.ProtoReflect.Descriptor instead.
func (*TeamApplicationAccessGrant) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{0}
}

func (x *TeamApplicationAccessGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamApplicationAccessGrant) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamApplicationAccessGrant) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *TeamApplicationAccessGrant) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

func (x *TeamApplicationAccessGrant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamApplicationAccessGrant) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TeamApplicationAccessGrant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TeamApplicationAccessGrant) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type CreateTeamApplicationAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the team to grant access to the application to
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the application to grant the team access to
	ApplicationId string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// The type of access that should be granted to the team
	AccessType    v1.TeamAccessType `protobuf:"varint,3,opt,name=access_type,json=accessType,proto3,enum=team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamApplicationAccessGrantRequest) Reset() {
	*x = CreateTeamApplicationAccessGrantRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamApplicationAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamApplicationAccessGrantRequest) ProtoMessage() {}

func (x *CreateTeamApplicationAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamApplicationAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamApplicationAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamApplicationAccessGrantRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateTeamApplicationAccessGrantRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateTeamApplicationAccessGrantRequest) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

type CreateTeamApplicationAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team access grant that was created
	TeamApplicationAccessGrant *TeamApplicationAccessGrant `protobuf:"bytes,1,opt,name=team_application_access_grant,json=teamApplicationAccessGrant,proto3" json:"team_application_access_grant,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateTeamApplicationAccessGrantResponse) Reset() {
	*x = CreateTeamApplicationAccessGrantResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamApplicationAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamApplicationAccessGrantResponse) ProtoMessage() {}

func (x *CreateTeamApplicationAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamApplicationAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamApplicationAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamApplicationAccessGrantResponse) GetTeamApplicationAccessGrant() *TeamApplicationAccessGrant {
	if x != nil {
		return x.TeamApplicationAccessGrant
	}
	return nil
}

type GetTeamApplicationAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamApplicationAccessGrantRequest) Reset() {
	*x = GetTeamApplicationAccessGrantRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamApplicationAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamApplicationAccessGrantRequest) ProtoMessage() {}

func (x *GetTeamApplicationAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamApplicationAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*GetTeamApplicationAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamApplicationAccessGrantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTeamApplicationAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team access grant
	TeamApplicationAccessGrant *TeamApplicationAccessGrant `protobuf:"bytes,1,opt,name=team_application_access_grant,json=teamApplicationAccessGrant,proto3" json:"team_application_access_grant,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetTeamApplicationAccessGrantResponse) Reset() {
	*x = GetTeamApplicationAccessGrantResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamApplicationAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamApplicationAccessGrantResponse) ProtoMessage() {}

func (x *GetTeamApplicationAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamApplicationAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*GetTeamApplicationAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamApplicationAccessGrantResponse) GetTeamApplicationAccessGrant() *TeamApplicationAccessGrant {
	if x != nil {
		return x.TeamApplicationAccessGrant
	}
	return nil
}

type ListTeamApplicationAccessGrantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a team to list all applications that the team has access to
	TeamId *string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	// The ID of an application to list all the teams that have access to it
	ApplicationId *string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3,oneof" json:"application_id,omitempty"`
	// The number of access grants on each page of results
	PageSize *int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// The token to retrieve the next page of results
	PageToken     *string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamApplicationAccessGrantsRequest) Reset() {
	*x = ListTeamApplicationAccessGrantsRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamApplicationAccessGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamApplicationAccessGrantsRequest) ProtoMessage() {}

func (x *ListTeamApplicationAccessGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamApplicationAccessGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamApplicationAccessGrantsRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeamApplicationAccessGrantsRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *ListTeamApplicationAccessGrantsRequest) GetApplicationId() string {
	if x != nil && x.ApplicationId != nil {
		return *x.ApplicationId
	}
	return ""
}

func (x *ListTeamApplicationAccessGrantsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListTeamApplicationAccessGrantsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListTeamApplicationAccessGrantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of team access grants
	TeamApplicationAccessGrants []*TeamApplicationAccessGrant `protobuf:"bytes,1,rep,name=team_application_access_grants,json=teamApplicationAccessGrants,proto3" json:"team_application_access_grants,omitempty"`
	// The token to retrieve the next page of results
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamApplicationAccessGrantsResponse) Reset() {
	*x = ListTeamApplicationAccessGrantsResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamApplicationAccessGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamApplicationAccessGrantsResponse) ProtoMessage() {}

func (x *ListTeamApplicationAccessGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamApplicationAccessGrantsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamApplicationAccessGrantsResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{6}
}

func (x *ListTeamApplicationAccessGrantsResponse) GetTeamApplicationAccessGrants() []*TeamApplicationAccessGrant {
	if x != nil {
		return x.TeamApplicationAccessGrants
	}
	return nil
}

func (x *ListTeamApplicationAccessGrantsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateTeamApplicationAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new type of access that should be granted to the team
	AccessType    v1.TeamAccessType `protobuf:"varint,2,opt,name=access_type,json=accessType,proto3,enum=team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamApplicationAccessGrantRequest) Reset() {
	*x = UpdateTeamApplicationAccessGrantRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamApplicationAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamApplicationAccessGrantRequest) ProtoMessage() {}

func (x *UpdateTeamApplicationAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamApplicationAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamApplicationAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTeamApplicationAccessGrantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeamApplicationAccessGrantRequest) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

type UpdateTeamApplicationAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated team access grant
	TeamApplicationAccessGrant *TeamApplicationAccessGrant `protobuf:"bytes,1,opt,name=team_application_access_grant,json=teamApplicationAccessGrant,proto3" json:"team_application_access_grant,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateTeamApplicationAccessGrantResponse) Reset() {
	*x = UpdateTeamApplicationAccessGrantResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamApplicationAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamApplicationAccessGrantResponse) ProtoMessage() {}

func (x *UpdateTeamApplicationAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamApplicationAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamApplicationAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTeamApplicationAccessGrantResponse) GetTeamApplicationAccessGrant() *TeamApplicationAccessGrant {
	if x != nil {
		return x.TeamApplicationAccessGrant
	}
	return nil
}

type DeleteTeamApplicationAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the team to whose access grant should be deleted
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the application whose access grant should be deleted
	ApplicationId string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamApplicationAccessGrantRequest) Reset() {
	*x = DeleteTeamApplicationAccessGrantRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamApplicationAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamApplicationAccessGrantRequest) ProtoMessage() {}

func (x *DeleteTeamApplicationAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamApplicationAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamApplicationAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTeamApplicationAccessGrantRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DeleteTeamApplicationAccessGrantRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type DeleteTeamApplicationAccessGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamApplicationAccessGrantResponse) Reset() {
	*x = DeleteTeamApplicationAccessGrantResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamApplicationAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamApplicationAccessGrantResponse) ProtoMessage() {}

func (x *DeleteTeamApplicationAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamApplicationAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamApplicationAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{10}
}

type DeleteTeamApplicationAccessGrantByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamApplicationAccessGrantByIdRequest) Reset() {
	*x = DeleteTeamApplicationAccessGrantByIdRequest{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamApplicationAccessGrantByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamApplicationAccessGrantByIdRequest) ProtoMessage() {}

func (x *DeleteTeamApplicationAccessGrantByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamApplicationAccessGrantByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamApplicationAccessGrantByIdRequest) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTeamApplicationAccessGrantByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeamApplicationAccessGrantByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamApplicationAccessGrantByIdResponse) Reset() {
	*x = DeleteTeamApplicationAccessGrantByIdResponse{}
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamApplicationAccessGrantByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamApplicationAccessGrantByIdResponse) ProtoMessage() {}

func (x *DeleteTeamApplicationAccessGrantByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamApplicationAccessGrantByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamApplicationAccessGrantByIdResponse) Descriptor() ([]byte, []int) {
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP(), []int{12}
}

var File_team_application_access_grant_v1_team_application_access_grant_proto protoreflect.FileDescriptor

const file_team_application_access_grant_v1_team_application_access_grant_proto_rawDesc = "" +
	"\n" +
	"Dteam_application_access_grant/v1/team_application_access_grant.proto\x12 team_application_access_grant.v1\x1a\x14authz/v1/authz.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*team_access_type/v1/team_access_type.proto\"\xe6\x02\n" +
	"\x1aTeamApplicationAccessGrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\x12D\n" +
	"\vaccess_type\x18\x04 \x01(\x0e2#.team_access_type.v1.TeamAccessTypeR\n" +
	"accessType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\xbe\x01\n" +
	"'CreateTeamApplicationAccessGrantRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12*\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\x03\xe0A\x02R\rapplicationId\x12I\n" +
	"\vaccess_type\x18\x03 \x01(\x0e2#.team_access_type.v1.TeamAccessTypeB\x03\xe0A\x02R\n" +
	"accessType\"\xab\x01\n" +
	"(CreateTeamApplicationAccessGrantResponse\x12\x7f\n" +
	"\x1dteam_application_access_grant\x18\x01 \x01(\v2<.team_application_access_grant.v1.TeamApplicationAccessGrantR\x1ateamApplicationAccessGrant\";\n" +
	"$GetTeamApplicationAccessGrantRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\xa8\x01\n" +
	"%GetTeamApplicationAccessGrantResponse\x12\x7f\n" +
	"\x1dteam_application_access_grant\x18\x01 \x01(\v2<.team_application_access_grant.v1.TeamApplicationAccessGrantR\x1ateamApplicationAccessGrant\"\xf4\x01\n" +
	"&ListTeamApplicationAccessGrantsRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tH\x00R\x06teamId\x88\x01\x01\x12*\n" +
	"\x0eapplication_id\x18\x02 \x01(\tH\x01R\rapplicationId\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x02R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x03R\tpageToken\x88\x01\x01B\n" +
	"\n" +
	"\b_team_idB\x11\n" +
	"\x0f_application_idB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xee\x01\n" +
	"'ListTeamApplicationAccessGrantsResponse\x12\x81\x01\n" +
	"\x1eteam_application_access_grants\x18\x01 \x03(\v2<.team_application_access_grant.v1.TeamApplicationAccessGrantR\x1bteamApplicationAccessGrants\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\x89\x01\n" +
	"'UpdateTeamApplicationAccessGrantRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12I\n" +
	"\vaccess_type\x18\x02 \x01(\x0e2#.team_access_type.v1.TeamAccessTypeB\x03\xe0A\x02R\n" +
	"accessType\"\xab\x01\n" +
	"(UpdateTeamApplicationAccessGrantResponse\x12\x7f\n" +
	"\x1dteam_application_access_grant\x18\x01 \x01(\v2<.team_application_access_grant.v1.TeamApplicationAccessGrantR\x1ateamApplicationAccessGrant\"s\n" +
	"'DeleteTeamApplicationAccessGrantRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12*\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\x03\xe0A\x02R\rapplicationId\"*\n" +
	"(DeleteTeamApplicationAccessGrantResponse\"B\n" +
	"+DeleteTeamApplicationAccessGrantByIdRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\".\n" +
	",DeleteTeamApplicationAccessGrantByIdResponse2\xdd\t\n" +
	"!TeamApplicationAccessGrantService\x12\xc6\x01\n" +
	" CreateTeamApplicationAccessGrant\x12I.team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest\x1aJ.team_application_access_grant.v1.CreateTeamApplicationAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x06\x04\x12\xbf\x01\n" +
	"\x1dGetTeamApplicationAccessGrant\x12F.team_application_access_grant.v1.GetTeamApplicationAccessGrantRequest\x1aG.team_application_access_grant.v1.GetTeamApplicationAccessGrantResponse\"\r\x88\xb5\x18\x01\x92\xb5\x18\x05\x01\a\x06\x05\x04\x12\xc5\x01\n" +
	"\x1fListTeamApplicationAccessGrants\x12H.team_application_access_grant.v1.ListTeamApplicationAccessGrantsRequest\x1aI.team_application_access_grant.v1.ListTeamApplicationAccessGrantsResponse\"\r\x88\xb5\x18\x01\x92\xb5\x18\x05\x01\a\x06\x05\x04\x12\xc6\x01\n" +
	" UpdateTeamApplicationAccessGrant\x12I.team_application_access_grant.v1.UpdateTeamApplicationAccessGrantRequest\x1aJ.team_application_access_grant.v1.UpdateTeamApplicationAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x06\x04\x12\xc6\x01\n" +
	" DeleteTeamApplicationAccessGrant\x12I.team_application_access_grant.v1.DeleteTeamApplicationAccessGrantRequest\x1aJ.team_application_access_grant.v1.DeleteTeamApplicationAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x06\x04\x12\xd2\x01\n" +
	"$DeleteTeamApplicationAccessGrantById\x12M.team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdRequest\x1aN.team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x06\x04BlZjgithub.com/terrabase-dev/terrabase-sdk/specs/team_application_access_grant/v1;teamApplicationAccessGrantv1b\x06proto3"

var (
	file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescOnce sync.Once
	file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescData []byte
)

func file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescGZIP() []byte {
	file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescOnce.Do(func() {
		file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_application_access_grant_v1_team_application_access_grant_proto_rawDesc), len(file_team_application_access_grant_v1_team_application_access_grant_proto_rawDesc)))
	})
	return file_team_application_access_grant_v1_team_application_access_grant_proto_rawDescData
}

var file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_team_application_access_grant_v1_team_application_access_grant_proto_goTypes = []any{
	(*TeamApplicationAccessGrant)(nil),                   // 0: team_application_access_grant.v1.TeamApplicationAccessGrant
	(*CreateTeamApplicationAccessGrantRequest)(nil),      // 1: team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	(*CreateTeamApplicationAccessGrantResponse)(nil),     // 2: team_application_access_grant.v1.CreateTeamApplicationAccessGrantResponse
	(*GetTeamApplicationAccessGrantRequest)(nil),         // 3: team_application_access_grant.v1.GetTeamApplicationAccessGrantRequest
	(*GetTeamApplicationAccessGrantResponse)(nil),        // 4: team_application_access_grant.v1.GetTeamApplicationAccessGrantResponse
	(*ListTeamApplicationAccessGrantsRequest)(nil),       // 5: team_application_access_grant.v1.ListTeamApplicationAccessGrantsRequest
	(*ListTeamApplicationAccessGrantsResponse)(nil),      // 6: team_application_access_grant.v1.ListTeamApplicationAccessGrantsResponse
	(*UpdateTeamApplicationAccessGrantRequest)(nil),      // 7: team_application_access_grant.v1.UpdateTeamApplicationAccessGrantRequest
	(*UpdateTeamApplicationAccessGrantResponse)(nil),     // 8: team_application_access_grant.v1.UpdateTeamApplicationAccessGrantResponse
	(*DeleteTeamApplicationAccessGrantRequest)(nil),      // 9: team_application_access_grant.v1.DeleteTeamApplicationAccessGrantRequest
	(*DeleteTeamApplicationAccessGrantResponse)(nil),     // 10: team_application_access_grant.v1.DeleteTeamApplicationAccessGrantResponse
	(*DeleteTeamApplicationAccessGrantByIdRequest)(nil),  // 11: team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdRequest
	(*DeleteTeamApplicationAccessGrantByIdResponse)(nil), // 12: team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdResponse
	(v1.TeamAccessType)(0),                               // 13: team_access_type.v1.TeamAccessType
	(*timestamppb.Timestamp)(nil),                        // 14: google.protobuf.Timestamp
}
var file_team_application_access_grant_v1_team_application_access_grant_proto_depIdxs = []int32{
	13, // 0: team_application_access_grant.v1.TeamApplicationAccessGrant.access_type:type_name -> team_access_type.v1.TeamAccessType
	14, // 1: team_application_access_grant.v1.TeamApplicationAccessGrant.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: team_application_access_grant.v1.TeamApplicationAccessGrant.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest.access_type:type_name -> team_access_type.v1.TeamAccessType
	0,  // 4: team_application_access_grant.v1.CreateTeamApplicationAccessGrantResponse.team_application_access_grant:type_name -> team_application_access_grant.v1.TeamApplicationAccessGrant
	0,  // 5: team_application_access_grant.v1.GetTeamApplicationAccessGrantResponse.team_application_access_grant:type_name -> team_application_access_grant.v1.TeamApplicationAccessGrant
	0,  // 6: team_application_access_grant.v1.ListTeamApplicationAccessGrantsResponse.team_application_access_grants:type_name -> team_application_access_grant.v1.TeamApplicationAccessGrant
	13, // 7: team_application_access_grant.v1.UpdateTeamApplicationAccessGrantRequest.access_type:type_name -> team_access_type.v1.TeamAccessType
	0,  // 8: team_application_access_grant.v1.UpdateTeamApplicationAccessGrantResponse.team_application_access_grant:type_name -> team_application_access_grant.v1.TeamApplicationAccessGrant
	1,  // 9: team_application_access_grant.v1.TeamApplicationAccessGrantService.CreateTeamApplicationAccessGrant:input_type -> team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	3,  // 10: team_application_access_grant.v1.TeamApplicationAccessGrantService.GetTeamApplicationAccessGrant:input_type -> team_application_access_grant.v1.GetTeamApplicationAccessGrantRequest
	5,  // 11: team_application_access_grant.v1.TeamApplicationAccessGrantService.ListTeamApplicationAccessGrants:input_type -> team_application_access_grant.v1.ListTeamApplicationAccessGrantsRequest
	7,  // 12: team_application_access_grant.v1.TeamApplicationAccessGrantService.UpdateTeamApplicationAccessGrant:input_type -> team_application_access_grant.v1.UpdateTeamApplicationAccessGrantRequest
	9,  // 13: team_application_access_grant.v1.TeamApplicationAccessGrantService.DeleteTeamApplicationAccessGrant:input_type -> team_application_access_grant.v1.DeleteTeamApplicationAccessGrantRequest
	11, // 14: team_application_access_grant.v1.TeamApplicationAccessGrantService.DeleteTeamApplicationAccessGrantById:input_type -> team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdRequest
	2,  // 15: team_application_access_grant.v1.TeamApplicationAccessGrantService.CreateTeamApplicationAccessGrant:output_type -> team_application_access_grant.v1.CreateTeamApplicationAccessGrantResponse
	4,  // 16: team_application_access_grant.v1.TeamApplicationAccessGrantService.GetTeamApplicationAccessGrant:output_type -> team_application_access_grant.v1.GetTeamApplicationAccessGrantResponse
	6,  // 17: team_application_access_grant.v1.TeamApplicationAccessGrantService.ListTeamApplicationAccessGrants:output_type -> team_application_access_grant.v1.ListTeamApplicationAccessGrantsResponse
	8,  // 18: team_application_access_grant.v1.TeamApplicationAccessGrantService.UpdateTeamApplicationAccessGrant:output_type -> team_application_access_grant.v1.UpdateTeamApplicationAccessGrantResponse
	10, // 19: team_application_access_grant.v1.TeamApplicationAccessGrantService.DeleteTeamApplicationAccessGrant:output_type -> team_application_access_grant.v1.DeleteTeamApplicationAccessGrantResponse
	12, // 20: team_application_access_grant.v1.TeamApplicationAccessGrantService.DeleteTeamApplicationAccessGrantById:output_type -> team_application_access_grant.v1.DeleteTeamApplicationAccessGrantByIdResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_team_application_access_grant_v1_team_application_access_grant_proto_init() }
func file_team_application_access_grant_v1_team_application_access_grant_proto_init() {
	if File_team_application_access_grant_v1_team_application_access_grant_proto != nil {
		return
	}
	file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[5].OneofWrappers = []any{}
	file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_application_access_grant_v1_team_application_access_grant_proto_rawDesc), len(file_team_application_access_grant_v1_team_application_access_grant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_application_access_grant_v1_team_application_access_grant_proto_goTypes,
		DependencyIndexes: file_team_application_access_grant_v1_team_application_access_grant_proto_depIdxs,
		MessageInfos:      file_team_application_access_grant_v1_team_application_access_grant_proto_msgTypes,
	}.Build()
	File_team_application_access_grant_v1_team_application_access_grant_proto = out.File
	file_team_application_access_grant_v1_team_application_access_grant_proto_goTypes = nil
	file_team_application_access_grant_v1_team_application_access_grant_proto_depIdxs = nil
}
