name: Lint PR Commits

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Check PR title
        run: |
          npm install --no-save @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          echo "${{ github.event.pull_request.title }}" | npx commitlint --config commitlint.config.js
